package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticCartInfo;

public interface AquaticCartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    int insert(AquaticCartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticCartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    AquaticCartInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticCartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_cart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticCartInfo record);
}