package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticRefundCsInfo;

public interface AquaticRefundCsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    int insert(AquaticRefundCsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticRefundCsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    AquaticRefundCsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticRefundCsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_cs_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticRefundCsInfo record);
}