package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticUserAddressInfo;

public interface AquaticUserAddressInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    int insert(AquaticUserAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticUserAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    AquaticUserAddressInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticUserAddressInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_user_address_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticUserAddressInfo record);
}