package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticRefundApplyInfo;

public interface AquaticRefundApplyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    int insert(AquaticRefundApplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticRefundApplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    AquaticRefundApplyInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticRefundApplyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_apply_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticRefundApplyInfo record);
}