package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticSaleBillboard;

public interface AquaticSaleBillboardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer billboardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    int insert(AquaticSaleBillboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    int insertSelective(AquaticSaleBillboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    AquaticSaleBillboard selectByPrimaryKey(Integer billboardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticSaleBillboard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_sale_billboard
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticSaleBillboard record);
}