package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticShopSettleInfo;

public interface AquaticShopSettleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    int insert(AquaticShopSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticShopSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    AquaticShopSettleInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticShopSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_settle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticShopSettleInfo record);
}