package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticShopOrderRecord;

public interface AquaticShopOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    int insert(AquaticShopOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    int insertSelective(AquaticShopOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    AquaticShopOrderRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticShopOrderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_shop_order_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticShopOrderRecord record);
}