package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticSettleFailInfo;

public interface AquaticSettleFailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    int insert(AquaticSettleFailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticSettleFailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    AquaticSettleFailInfo selectByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticSettleFailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_fail_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticSettleFailInfo record);
}