package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticSettleCardInfo;

public interface AquaticSettleCardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    int insert(AquaticSettleCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticSettleCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    AquaticSettleCardInfo selectByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticSettleCardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_card_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticSettleCardInfo record);
}