package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticPosPayRecord;
import com.haozi.demo.springboot.bean.po.AquaticPosPayRecordKey;

public interface AquaticPosPayRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(AquaticPosPayRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    int insert(AquaticPosPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    int insertSelective(AquaticPosPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    AquaticPosPayRecord selectByPrimaryKey(AquaticPosPayRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticPosPayRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_pos_pay_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticPosPayRecord record);
}