package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticRefundAffixInfo;

public interface AquaticRefundAffixInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    int insert(AquaticRefundAffixInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticRefundAffixInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    AquaticRefundAffixInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticRefundAffixInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_refund_affix_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticRefundAffixInfo record);
}