package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticCategoryInfo;

public interface AquaticCategoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    int insert(AquaticCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    AquaticCategoryInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticCategoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_category_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticCategoryInfo record);
}