package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticOrderBillInfo;

public interface AquaticOrderBillInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    int insert(AquaticOrderBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticOrderBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    AquaticOrderBillInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticOrderBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_bill_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticOrderBillInfo record);
}