package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticSettleSuccessInfo;

public interface AquaticSettleSuccessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    int insert(AquaticSettleSuccessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticSettleSuccessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    AquaticSettleSuccessInfo selectByPrimaryKey(String settleKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticSettleSuccessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_settle_success_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticSettleSuccessInfo record);
}