package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.AquaticOrderGoodsInfo;

public interface AquaticOrderGoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    int insert(AquaticOrderGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticOrderGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    AquaticOrderGoodsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticOrderGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_goods_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticOrderGoodsInfo record);
}