package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.BankAccountInfo;

public interface BankAccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    int insert(BankAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    int insertSelective(BankAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    BankAccountInfo selectByPrimaryKey(Integer accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BankAccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bank_account_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BankAccountInfo record);
}