package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.DelayedSettleInfo;
import com.haozi.demo.springboot.bean.po.DelayedSettleInfoKey;

public interface DelayedSettleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DelayedSettleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    int insert(DelayedSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    int insertSelective(DelayedSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    DelayedSettleInfo selectByPrimaryKey(DelayedSettleInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DelayedSettleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table delayed_settle_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DelayedSettleInfo record);
}