package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.EndOrderRateInfo;

public interface EndOrderRateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    int insert(EndOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    int insertSelective(EndOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    EndOrderRateInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EndOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table end_order_rate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EndOrderRateInfo record);
}