package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.PlatOrderRateInfo;

public interface PlatOrderRateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    int insert(PlatOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    int insertSelective(PlatOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    PlatOrderRateInfo selectByPrimaryKey(String orderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PlatOrderRateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plat_order_rate_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PlatOrderRateInfo record);
}