package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.QrtzSimpropTriggers;
import com.haozi.demo.springboot.bean.po.QrtzSimpropTriggersKey;

public interface QrtzSimpropTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insert(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int insertSelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    QrtzSimpropTriggers selectByPrimaryKey(QrtzSimpropTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzSimpropTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_simprop_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzSimpropTriggers record);
}