package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.QrtzSchedulerState;
import com.haozi.demo.springboot.bean.po.QrtzSchedulerStateKey;

public interface QrtzSchedulerStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insert(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int insertSelective(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    QrtzSchedulerState selectByPrimaryKey(QrtzSchedulerStateKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzSchedulerState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_scheduler_state
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzSchedulerState record);
}