package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.QrtzBlobTriggers;
import com.haozi.demo.springboot.bean.po.QrtzBlobTriggersKey;

public interface QrtzBlobTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int insert(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int insertSelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    QrtzBlobTriggers selectByPrimaryKey(QrtzBlobTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzBlobTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_blob_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QrtzBlobTriggers record);
}