package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.QrtzTriggers;
import com.haozi.demo.springboot.bean.po.QrtzTriggersKey;

public interface QrtzTriggersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insert(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int insertSelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    QrtzTriggers selectByPrimaryKey(QrtzTriggersKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(QrtzTriggers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_triggers
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QrtzTriggers record);
}