package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.TposQueryInfo;
import com.haozi.demo.springboot.bean.po.TposQueryInfoKey;

public interface TposQueryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TposQueryInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    int insert(TposQueryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    int insertSelective(TposQueryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    TposQueryInfo selectByPrimaryKey(TposQueryInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TposQueryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tpos_query_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TposQueryInfo record);
}