package com.haozi.demo.springboot.dao;

import com.haozi.demo.springboot.bean.po.TradeChannelInfo;

public interface TradeChannelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer tradeChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    int insert(TradeChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    int insertSelective(TradeChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    TradeChannelInfo selectByPrimaryKey(Integer tradeChannelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_channel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeChannelInfo record);
}