package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticPayOrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.pay_order_code
     *
     * @mbggenerated
     */
    private String payOrderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.SEND_TIME
     *
     * @mbggenerated
     */
    private Date sendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.DEAL_TIME
     *
     * @mbggenerated
     */
    private Date dealTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.SHOP_CODE
     *
     * @mbggenerated
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_WAY
     *
     * @mbggenerated
     */
    private String payWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_MONEY
     *
     * @mbggenerated
     */
    private Long payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_TYPE
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.USER_KEY
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    private String tradeQueryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_ACCOUNT
     *
     * @mbggenerated
     */
    private String payAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_CURRENCY
     *
     * @mbggenerated
     */
    private String payCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.BANK_TYPE
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.TRADE_TYPE
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pay_order_info.PAY_INFO
     *
     * @mbggenerated
     */
    private String payInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.id
     *
     * @return the value of aquatic_pay_order_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.id
     *
     * @param id the value for aquatic_pay_order_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.pay_order_code
     *
     * @return the value of aquatic_pay_order_info.pay_order_code
     *
     * @mbggenerated
     */
    public String getPayOrderCode() {
        return payOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.pay_order_code
     *
     * @param payOrderCode the value for aquatic_pay_order_info.pay_order_code
     *
     * @mbggenerated
     */
    public void setPayOrderCode(String payOrderCode) {
        this.payOrderCode = payOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.SEND_TIME
     *
     * @return the value of aquatic_pay_order_info.SEND_TIME
     *
     * @mbggenerated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.SEND_TIME
     *
     * @param sendTime the value for aquatic_pay_order_info.SEND_TIME
     *
     * @mbggenerated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.DEAL_TIME
     *
     * @return the value of aquatic_pay_order_info.DEAL_TIME
     *
     * @mbggenerated
     */
    public Date getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.DEAL_TIME
     *
     * @param dealTime the value for aquatic_pay_order_info.DEAL_TIME
     *
     * @mbggenerated
     */
    public void setDealTime(Date dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.ORDER_STATUS
     *
     * @return the value of aquatic_pay_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.ORDER_STATUS
     *
     * @param orderStatus the value for aquatic_pay_order_info.ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.SHOP_CODE
     *
     * @return the value of aquatic_pay_order_info.SHOP_CODE
     *
     * @mbggenerated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.SHOP_CODE
     *
     * @param shopCode the value for aquatic_pay_order_info.SHOP_CODE
     *
     * @mbggenerated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_WAY
     *
     * @return the value of aquatic_pay_order_info.PAY_WAY
     *
     * @mbggenerated
     */
    public String getPayWay() {
        return payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_WAY
     *
     * @param payWay the value for aquatic_pay_order_info.PAY_WAY
     *
     * @mbggenerated
     */
    public void setPayWay(String payWay) {
        this.payWay = payWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_MONEY
     *
     * @return the value of aquatic_pay_order_info.PAY_MONEY
     *
     * @mbggenerated
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_MONEY
     *
     * @param payMoney the value for aquatic_pay_order_info.PAY_MONEY
     *
     * @mbggenerated
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_TYPE
     *
     * @return the value of aquatic_pay_order_info.PAY_TYPE
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_TYPE
     *
     * @param payType the value for aquatic_pay_order_info.PAY_TYPE
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.USER_KEY
     *
     * @return the value of aquatic_pay_order_info.USER_KEY
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.USER_KEY
     *
     * @param userKey the value for aquatic_pay_order_info.USER_KEY
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.TRADE_QUERY_CODE
     *
     * @return the value of aquatic_pay_order_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    public String getTradeQueryCode() {
        return tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.TRADE_QUERY_CODE
     *
     * @param tradeQueryCode the value for aquatic_pay_order_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    public void setTradeQueryCode(String tradeQueryCode) {
        this.tradeQueryCode = tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_ACCOUNT
     *
     * @return the value of aquatic_pay_order_info.PAY_ACCOUNT
     *
     * @mbggenerated
     */
    public String getPayAccount() {
        return payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_ACCOUNT
     *
     * @param payAccount the value for aquatic_pay_order_info.PAY_ACCOUNT
     *
     * @mbggenerated
     */
    public void setPayAccount(String payAccount) {
        this.payAccount = payAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_CURRENCY
     *
     * @return the value of aquatic_pay_order_info.PAY_CURRENCY
     *
     * @mbggenerated
     */
    public String getPayCurrency() {
        return payCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_CURRENCY
     *
     * @param payCurrency the value for aquatic_pay_order_info.PAY_CURRENCY
     *
     * @mbggenerated
     */
    public void setPayCurrency(String payCurrency) {
        this.payCurrency = payCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.BANK_TYPE
     *
     * @return the value of aquatic_pay_order_info.BANK_TYPE
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.BANK_TYPE
     *
     * @param bankType the value for aquatic_pay_order_info.BANK_TYPE
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.TRADE_TYPE
     *
     * @return the value of aquatic_pay_order_info.TRADE_TYPE
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.TRADE_TYPE
     *
     * @param tradeType the value for aquatic_pay_order_info.TRADE_TYPE
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pay_order_info.PAY_INFO
     *
     * @return the value of aquatic_pay_order_info.PAY_INFO
     *
     * @mbggenerated
     */
    public String getPayInfo() {
        return payInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pay_order_info.PAY_INFO
     *
     * @param payInfo the value for aquatic_pay_order_info.PAY_INFO
     *
     * @mbggenerated
     */
    public void setPayInfo(String payInfo) {
        this.payInfo = payInfo;
    }
}