package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticShopSettleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.settle_day
     *
     * @mbggenerated
     */
    private Date settleDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.settle_money
     *
     * @mbggenerated
     */
    private Long settleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.user_key
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.settle_date
     *
     * @mbggenerated
     */
    private Date settleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_settle_info.settle_status
     *
     * @mbggenerated
     */
    private String settleStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.id
     *
     * @return the value of aquatic_shop_settle_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.id
     *
     * @param id the value for aquatic_shop_settle_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.settle_day
     *
     * @return the value of aquatic_shop_settle_info.settle_day
     *
     * @mbggenerated
     */
    public Date getSettleDay() {
        return settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.settle_day
     *
     * @param settleDay the value for aquatic_shop_settle_info.settle_day
     *
     * @mbggenerated
     */
    public void setSettleDay(Date settleDay) {
        this.settleDay = settleDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.settle_money
     *
     * @return the value of aquatic_shop_settle_info.settle_money
     *
     * @mbggenerated
     */
    public Long getSettleMoney() {
        return settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.settle_money
     *
     * @param settleMoney the value for aquatic_shop_settle_info.settle_money
     *
     * @mbggenerated
     */
    public void setSettleMoney(Long settleMoney) {
        this.settleMoney = settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.order_code
     *
     * @return the value of aquatic_shop_settle_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.order_code
     *
     * @param orderCode the value for aquatic_shop_settle_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.user_key
     *
     * @return the value of aquatic_shop_settle_info.user_key
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.user_key
     *
     * @param userKey the value for aquatic_shop_settle_info.user_key
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.shop_key
     *
     * @return the value of aquatic_shop_settle_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.shop_key
     *
     * @param shopKey the value for aquatic_shop_settle_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.settle_date
     *
     * @return the value of aquatic_shop_settle_info.settle_date
     *
     * @mbggenerated
     */
    public Date getSettleDate() {
        return settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.settle_date
     *
     * @param settleDate the value for aquatic_shop_settle_info.settle_date
     *
     * @mbggenerated
     */
    public void setSettleDate(Date settleDate) {
        this.settleDate = settleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_settle_info.settle_status
     *
     * @return the value of aquatic_shop_settle_info.settle_status
     *
     * @mbggenerated
     */
    public String getSettleStatus() {
        return settleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_settle_info.settle_status
     *
     * @param settleStatus the value for aquatic_shop_settle_info.settle_status
     *
     * @mbggenerated
     */
    public void setSettleStatus(String settleStatus) {
        this.settleStatus = settleStatus;
    }
}