package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticOrderBillInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_key
     *
     * @mbggenerated
     */
    private String billKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.user_key
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_tittle
     *
     * @mbggenerated
     */
    private String billTittle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.taxpayer_id
     *
     * @mbggenerated
     */
    private String taxpayerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.opening_bank
     *
     * @mbggenerated
     */
    private String openingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.biill_account
     *
     * @mbggenerated
     */
    private String biillAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.biil_address
     *
     * @mbggenerated
     */
    private String biilAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_tel
     *
     * @mbggenerated
     */
    private String billTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.is_open
     *
     * @mbggenerated
     */
    private String isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_code
     *
     * @mbggenerated
     */
    private String billCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.express_company
     *
     * @mbggenerated
     */
    private String expressCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.express_code
     *
     * @mbggenerated
     */
    private String expressCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.express_time
     *
     * @mbggenerated
     */
    private Date expressTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_type
     *
     * @mbggenerated
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_bill_info.bill_context
     *
     * @mbggenerated
     */
    private String billContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.id
     *
     * @return the value of aquatic_order_bill_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.id
     *
     * @param id the value for aquatic_order_bill_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_key
     *
     * @return the value of aquatic_order_bill_info.bill_key
     *
     * @mbggenerated
     */
    public String getBillKey() {
        return billKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_key
     *
     * @param billKey the value for aquatic_order_bill_info.bill_key
     *
     * @mbggenerated
     */
    public void setBillKey(String billKey) {
        this.billKey = billKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.user_key
     *
     * @return the value of aquatic_order_bill_info.user_key
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.user_key
     *
     * @param userKey the value for aquatic_order_bill_info.user_key
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.order_code
     *
     * @return the value of aquatic_order_bill_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.order_code
     *
     * @param orderCode the value for aquatic_order_bill_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_tittle
     *
     * @return the value of aquatic_order_bill_info.bill_tittle
     *
     * @mbggenerated
     */
    public String getBillTittle() {
        return billTittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_tittle
     *
     * @param billTittle the value for aquatic_order_bill_info.bill_tittle
     *
     * @mbggenerated
     */
    public void setBillTittle(String billTittle) {
        this.billTittle = billTittle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.taxpayer_id
     *
     * @return the value of aquatic_order_bill_info.taxpayer_id
     *
     * @mbggenerated
     */
    public String getTaxpayerId() {
        return taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.taxpayer_id
     *
     * @param taxpayerId the value for aquatic_order_bill_info.taxpayer_id
     *
     * @mbggenerated
     */
    public void setTaxpayerId(String taxpayerId) {
        this.taxpayerId = taxpayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.opening_bank
     *
     * @return the value of aquatic_order_bill_info.opening_bank
     *
     * @mbggenerated
     */
    public String getOpeningBank() {
        return openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.opening_bank
     *
     * @param openingBank the value for aquatic_order_bill_info.opening_bank
     *
     * @mbggenerated
     */
    public void setOpeningBank(String openingBank) {
        this.openingBank = openingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.biill_account
     *
     * @return the value of aquatic_order_bill_info.biill_account
     *
     * @mbggenerated
     */
    public String getBiillAccount() {
        return biillAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.biill_account
     *
     * @param biillAccount the value for aquatic_order_bill_info.biill_account
     *
     * @mbggenerated
     */
    public void setBiillAccount(String biillAccount) {
        this.biillAccount = biillAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.biil_address
     *
     * @return the value of aquatic_order_bill_info.biil_address
     *
     * @mbggenerated
     */
    public String getBiilAddress() {
        return biilAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.biil_address
     *
     * @param biilAddress the value for aquatic_order_bill_info.biil_address
     *
     * @mbggenerated
     */
    public void setBiilAddress(String biilAddress) {
        this.biilAddress = biilAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_tel
     *
     * @return the value of aquatic_order_bill_info.bill_tel
     *
     * @mbggenerated
     */
    public String getBillTel() {
        return billTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_tel
     *
     * @param billTel the value for aquatic_order_bill_info.bill_tel
     *
     * @mbggenerated
     */
    public void setBillTel(String billTel) {
        this.billTel = billTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.status
     *
     * @return the value of aquatic_order_bill_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.status
     *
     * @param status the value for aquatic_order_bill_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.add_time
     *
     * @return the value of aquatic_order_bill_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.add_time
     *
     * @param addTime the value for aquatic_order_bill_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.is_open
     *
     * @return the value of aquatic_order_bill_info.is_open
     *
     * @mbggenerated
     */
    public String getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.is_open
     *
     * @param isOpen the value for aquatic_order_bill_info.is_open
     *
     * @mbggenerated
     */
    public void setIsOpen(String isOpen) {
        this.isOpen = isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_code
     *
     * @return the value of aquatic_order_bill_info.bill_code
     *
     * @mbggenerated
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_code
     *
     * @param billCode the value for aquatic_order_bill_info.bill_code
     *
     * @mbggenerated
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.express_company
     *
     * @return the value of aquatic_order_bill_info.express_company
     *
     * @mbggenerated
     */
    public String getExpressCompany() {
        return expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.express_company
     *
     * @param expressCompany the value for aquatic_order_bill_info.express_company
     *
     * @mbggenerated
     */
    public void setExpressCompany(String expressCompany) {
        this.expressCompany = expressCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.express_code
     *
     * @return the value of aquatic_order_bill_info.express_code
     *
     * @mbggenerated
     */
    public String getExpressCode() {
        return expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.express_code
     *
     * @param expressCode the value for aquatic_order_bill_info.express_code
     *
     * @mbggenerated
     */
    public void setExpressCode(String expressCode) {
        this.expressCode = expressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.express_time
     *
     * @return the value of aquatic_order_bill_info.express_time
     *
     * @mbggenerated
     */
    public Date getExpressTime() {
        return expressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.express_time
     *
     * @param expressTime the value for aquatic_order_bill_info.express_time
     *
     * @mbggenerated
     */
    public void setExpressTime(Date expressTime) {
        this.expressTime = expressTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_type
     *
     * @return the value of aquatic_order_bill_info.bill_type
     *
     * @mbggenerated
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_type
     *
     * @param billType the value for aquatic_order_bill_info.bill_type
     *
     * @mbggenerated
     */
    public void setBillType(String billType) {
        this.billType = billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_bill_info.bill_context
     *
     * @return the value of aquatic_order_bill_info.bill_context
     *
     * @mbggenerated
     */
    public String getBillContext() {
        return billContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_bill_info.bill_context
     *
     * @param billContext the value for aquatic_order_bill_info.bill_context
     *
     * @mbggenerated
     */
    public void setBillContext(String billContext) {
        this.billContext = billContext;
    }
}