package com.haozi.demo.springboot.bean.po;

public class AquaticRepetRecordInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.refund_key
     *
     * @mbggenerated
     */
    private String refundKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    private String tradeQueryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.PAY_ORDER_CODE
     *
     * @mbggenerated
     */
    private String payOrderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.REFUND_CODE
     *
     * @mbggenerated
     */
    private String refundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.REFUND_MONEY
     *
     * @mbggenerated
     */
    private Long refundMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.USER_KEY
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.SHOP_KEY
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.PAYWAY
     *
     * @mbggenerated
     */
    private String payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.REFUND_STATUS
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.STATUS_CODE
     *
     * @mbggenerated
     */
    private String statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_repet_record_info.REFUND_DATE
     *
     * @mbggenerated
     */
    private String refundDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.ID
     *
     * @return the value of aquatic_repet_record_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.ID
     *
     * @param id the value for aquatic_repet_record_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.refund_key
     *
     * @return the value of aquatic_repet_record_info.refund_key
     *
     * @mbggenerated
     */
    public String getRefundKey() {
        return refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.refund_key
     *
     * @param refundKey the value for aquatic_repet_record_info.refund_key
     *
     * @mbggenerated
     */
    public void setRefundKey(String refundKey) {
        this.refundKey = refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.order_code
     *
     * @return the value of aquatic_repet_record_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.order_code
     *
     * @param orderCode the value for aquatic_repet_record_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.TRADE_QUERY_CODE
     *
     * @return the value of aquatic_repet_record_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    public String getTradeQueryCode() {
        return tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.TRADE_QUERY_CODE
     *
     * @param tradeQueryCode the value for aquatic_repet_record_info.TRADE_QUERY_CODE
     *
     * @mbggenerated
     */
    public void setTradeQueryCode(String tradeQueryCode) {
        this.tradeQueryCode = tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.PAY_ORDER_CODE
     *
     * @return the value of aquatic_repet_record_info.PAY_ORDER_CODE
     *
     * @mbggenerated
     */
    public String getPayOrderCode() {
        return payOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.PAY_ORDER_CODE
     *
     * @param payOrderCode the value for aquatic_repet_record_info.PAY_ORDER_CODE
     *
     * @mbggenerated
     */
    public void setPayOrderCode(String payOrderCode) {
        this.payOrderCode = payOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.REFUND_CODE
     *
     * @return the value of aquatic_repet_record_info.REFUND_CODE
     *
     * @mbggenerated
     */
    public String getRefundCode() {
        return refundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.REFUND_CODE
     *
     * @param refundCode the value for aquatic_repet_record_info.REFUND_CODE
     *
     * @mbggenerated
     */
    public void setRefundCode(String refundCode) {
        this.refundCode = refundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.REFUND_MONEY
     *
     * @return the value of aquatic_repet_record_info.REFUND_MONEY
     *
     * @mbggenerated
     */
    public Long getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.REFUND_MONEY
     *
     * @param refundMoney the value for aquatic_repet_record_info.REFUND_MONEY
     *
     * @mbggenerated
     */
    public void setRefundMoney(Long refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.USER_KEY
     *
     * @return the value of aquatic_repet_record_info.USER_KEY
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.USER_KEY
     *
     * @param userKey the value for aquatic_repet_record_info.USER_KEY
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.SHOP_KEY
     *
     * @return the value of aquatic_repet_record_info.SHOP_KEY
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.SHOP_KEY
     *
     * @param shopKey the value for aquatic_repet_record_info.SHOP_KEY
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.PAYWAY
     *
     * @return the value of aquatic_repet_record_info.PAYWAY
     *
     * @mbggenerated
     */
    public String getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.PAYWAY
     *
     * @param payway the value for aquatic_repet_record_info.PAYWAY
     *
     * @mbggenerated
     */
    public void setPayway(String payway) {
        this.payway = payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.REFUND_STATUS
     *
     * @return the value of aquatic_repet_record_info.REFUND_STATUS
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.REFUND_STATUS
     *
     * @param refundStatus the value for aquatic_repet_record_info.REFUND_STATUS
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.STATUS_CODE
     *
     * @return the value of aquatic_repet_record_info.STATUS_CODE
     *
     * @mbggenerated
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.STATUS_CODE
     *
     * @param statusCode the value for aquatic_repet_record_info.STATUS_CODE
     *
     * @mbggenerated
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_repet_record_info.REFUND_DATE
     *
     * @return the value of aquatic_repet_record_info.REFUND_DATE
     *
     * @mbggenerated
     */
    public String getRefundDate() {
        return refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_repet_record_info.REFUND_DATE
     *
     * @param refundDate the value for aquatic_repet_record_info.REFUND_DATE
     *
     * @mbggenerated
     */
    public void setRefundDate(String refundDate) {
        this.refundDate = refundDate;
    }
}