package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticPosPayRecord extends AquaticPosPayRecordKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.auth_code
     *
     * @mbggenerated
     */
    private String authCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.batch_number
     *
     * @mbggenerated
     */
    private String batchNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.device_number
     *
     * @mbggenerated
     */
    private String deviceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.serial_number
     *
     * @mbggenerated
     */
    private String serialNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.customer_number
     *
     * @mbggenerated
     */
    private String customerNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.money
     *
     * @mbggenerated
     */
    private String money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.ret_info
     *
     * @mbggenerated
     */
    private String retInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.msg_info
     *
     * @mbggenerated
     */
    private String msgInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.channel_flowId
     *
     * @mbggenerated
     */
    private String channelFlowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.card_numer
     *
     * @mbggenerated
     */
    private String cardNumer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.pos_type
     *
     * @mbggenerated
     */
    private String posType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.customer_name
     *
     * @mbggenerated
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.deal_name
     *
     * @mbggenerated
     */
    private String dealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.faBank_code
     *
     * @mbggenerated
     */
    private String fabankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.cardEntry_time
     *
     * @mbggenerated
     */
    private Date cardentryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.backIc_data
     *
     * @mbggenerated
     */
    private String backicData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.transaction_time
     *
     * @mbggenerated
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.flow_id
     *
     * @mbggenerated
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.error_Code
     *
     * @mbggenerated
     */
    private String errorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_pos_pay_record.rever_Code
     *
     * @mbggenerated
     */
    private String reverCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.order_code
     *
     * @return the value of aquatic_pos_pay_record.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.order_code
     *
     * @param orderCode the value for aquatic_pos_pay_record.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.auth_code
     *
     * @return the value of aquatic_pos_pay_record.auth_code
     *
     * @mbggenerated
     */
    public String getAuthCode() {
        return authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.auth_code
     *
     * @param authCode the value for aquatic_pos_pay_record.auth_code
     *
     * @mbggenerated
     */
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.batch_number
     *
     * @return the value of aquatic_pos_pay_record.batch_number
     *
     * @mbggenerated
     */
    public String getBatchNumber() {
        return batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.batch_number
     *
     * @param batchNumber the value for aquatic_pos_pay_record.batch_number
     *
     * @mbggenerated
     */
    public void setBatchNumber(String batchNumber) {
        this.batchNumber = batchNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.device_number
     *
     * @return the value of aquatic_pos_pay_record.device_number
     *
     * @mbggenerated
     */
    public String getDeviceNumber() {
        return deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.device_number
     *
     * @param deviceNumber the value for aquatic_pos_pay_record.device_number
     *
     * @mbggenerated
     */
    public void setDeviceNumber(String deviceNumber) {
        this.deviceNumber = deviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.serial_number
     *
     * @return the value of aquatic_pos_pay_record.serial_number
     *
     * @mbggenerated
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.serial_number
     *
     * @param serialNumber the value for aquatic_pos_pay_record.serial_number
     *
     * @mbggenerated
     */
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.order_id
     *
     * @return the value of aquatic_pos_pay_record.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.order_id
     *
     * @param orderId the value for aquatic_pos_pay_record.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.customer_number
     *
     * @return the value of aquatic_pos_pay_record.customer_number
     *
     * @mbggenerated
     */
    public String getCustomerNumber() {
        return customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.customer_number
     *
     * @param customerNumber the value for aquatic_pos_pay_record.customer_number
     *
     * @mbggenerated
     */
    public void setCustomerNumber(String customerNumber) {
        this.customerNumber = customerNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.money
     *
     * @return the value of aquatic_pos_pay_record.money
     *
     * @mbggenerated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.money
     *
     * @param money the value for aquatic_pos_pay_record.money
     *
     * @mbggenerated
     */
    public void setMoney(String money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.ret_info
     *
     * @return the value of aquatic_pos_pay_record.ret_info
     *
     * @mbggenerated
     */
    public String getRetInfo() {
        return retInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.ret_info
     *
     * @param retInfo the value for aquatic_pos_pay_record.ret_info
     *
     * @mbggenerated
     */
    public void setRetInfo(String retInfo) {
        this.retInfo = retInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.msg_info
     *
     * @return the value of aquatic_pos_pay_record.msg_info
     *
     * @mbggenerated
     */
    public String getMsgInfo() {
        return msgInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.msg_info
     *
     * @param msgInfo the value for aquatic_pos_pay_record.msg_info
     *
     * @mbggenerated
     */
    public void setMsgInfo(String msgInfo) {
        this.msgInfo = msgInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.add_time
     *
     * @return the value of aquatic_pos_pay_record.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.add_time
     *
     * @param addTime the value for aquatic_pos_pay_record.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.channel_flowId
     *
     * @return the value of aquatic_pos_pay_record.channel_flowId
     *
     * @mbggenerated
     */
    public String getChannelFlowid() {
        return channelFlowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.channel_flowId
     *
     * @param channelFlowid the value for aquatic_pos_pay_record.channel_flowId
     *
     * @mbggenerated
     */
    public void setChannelFlowid(String channelFlowid) {
        this.channelFlowid = channelFlowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.card_numer
     *
     * @return the value of aquatic_pos_pay_record.card_numer
     *
     * @mbggenerated
     */
    public String getCardNumer() {
        return cardNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.card_numer
     *
     * @param cardNumer the value for aquatic_pos_pay_record.card_numer
     *
     * @mbggenerated
     */
    public void setCardNumer(String cardNumer) {
        this.cardNumer = cardNumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.card_type
     *
     * @return the value of aquatic_pos_pay_record.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.card_type
     *
     * @param cardType the value for aquatic_pos_pay_record.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.pos_type
     *
     * @return the value of aquatic_pos_pay_record.pos_type
     *
     * @mbggenerated
     */
    public String getPosType() {
        return posType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.pos_type
     *
     * @param posType the value for aquatic_pos_pay_record.pos_type
     *
     * @mbggenerated
     */
    public void setPosType(String posType) {
        this.posType = posType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.customer_name
     *
     * @return the value of aquatic_pos_pay_record.customer_name
     *
     * @mbggenerated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.customer_name
     *
     * @param customerName the value for aquatic_pos_pay_record.customer_name
     *
     * @mbggenerated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.deal_name
     *
     * @return the value of aquatic_pos_pay_record.deal_name
     *
     * @mbggenerated
     */
    public String getDealName() {
        return dealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.deal_name
     *
     * @param dealName the value for aquatic_pos_pay_record.deal_name
     *
     * @mbggenerated
     */
    public void setDealName(String dealName) {
        this.dealName = dealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.faBank_code
     *
     * @return the value of aquatic_pos_pay_record.faBank_code
     *
     * @mbggenerated
     */
    public String getFabankCode() {
        return fabankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.faBank_code
     *
     * @param fabankCode the value for aquatic_pos_pay_record.faBank_code
     *
     * @mbggenerated
     */
    public void setFabankCode(String fabankCode) {
        this.fabankCode = fabankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.cardEntry_time
     *
     * @return the value of aquatic_pos_pay_record.cardEntry_time
     *
     * @mbggenerated
     */
    public Date getCardentryTime() {
        return cardentryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.cardEntry_time
     *
     * @param cardentryTime the value for aquatic_pos_pay_record.cardEntry_time
     *
     * @mbggenerated
     */
    public void setCardentryTime(Date cardentryTime) {
        this.cardentryTime = cardentryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.backIc_data
     *
     * @return the value of aquatic_pos_pay_record.backIc_data
     *
     * @mbggenerated
     */
    public String getBackicData() {
        return backicData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.backIc_data
     *
     * @param backicData the value for aquatic_pos_pay_record.backIc_data
     *
     * @mbggenerated
     */
    public void setBackicData(String backicData) {
        this.backicData = backicData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.transaction_time
     *
     * @return the value of aquatic_pos_pay_record.transaction_time
     *
     * @mbggenerated
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.transaction_time
     *
     * @param transactionTime the value for aquatic_pos_pay_record.transaction_time
     *
     * @mbggenerated
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.flow_id
     *
     * @return the value of aquatic_pos_pay_record.flow_id
     *
     * @mbggenerated
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.flow_id
     *
     * @param flowId the value for aquatic_pos_pay_record.flow_id
     *
     * @mbggenerated
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.error_Code
     *
     * @return the value of aquatic_pos_pay_record.error_Code
     *
     * @mbggenerated
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.error_Code
     *
     * @param errorCode the value for aquatic_pos_pay_record.error_Code
     *
     * @mbggenerated
     */
    public void setErrorCode(String errorCode) {
        this.errorCode = errorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_pos_pay_record.rever_Code
     *
     * @return the value of aquatic_pos_pay_record.rever_Code
     *
     * @mbggenerated
     */
    public String getReverCode() {
        return reverCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_pos_pay_record.rever_Code
     *
     * @param reverCode the value for aquatic_pos_pay_record.rever_Code
     *
     * @mbggenerated
     */
    public void setReverCode(String reverCode) {
        this.reverCode = reverCode;
    }
}