package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticRefundAffixInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_affix_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_affix_info.refund_key
     *
     * @mbggenerated
     */
    private String refundKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_affix_info.affix_url
     *
     * @mbggenerated
     */
    private String affixUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_affix_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_affix_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_affix_info.id
     *
     * @return the value of aquatic_refund_affix_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_affix_info.id
     *
     * @param id the value for aquatic_refund_affix_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_affix_info.refund_key
     *
     * @return the value of aquatic_refund_affix_info.refund_key
     *
     * @mbggenerated
     */
    public String getRefundKey() {
        return refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_affix_info.refund_key
     *
     * @param refundKey the value for aquatic_refund_affix_info.refund_key
     *
     * @mbggenerated
     */
    public void setRefundKey(String refundKey) {
        this.refundKey = refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_affix_info.affix_url
     *
     * @return the value of aquatic_refund_affix_info.affix_url
     *
     * @mbggenerated
     */
    public String getAffixUrl() {
        return affixUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_affix_info.affix_url
     *
     * @param affixUrl the value for aquatic_refund_affix_info.affix_url
     *
     * @mbggenerated
     */
    public void setAffixUrl(String affixUrl) {
        this.affixUrl = affixUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_affix_info.add_time
     *
     * @return the value of aquatic_refund_affix_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_affix_info.add_time
     *
     * @param addTime the value for aquatic_refund_affix_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_affix_info.STATUS
     *
     * @return the value of aquatic_refund_affix_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_affix_info.STATUS
     *
     * @param status the value for aquatic_refund_affix_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }
}