package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticCartInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.cart_code
     *
     * @mbggenerated
     */
    private String cartCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.user_key
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.goods_key
     *
     * @mbggenerated
     */
    private String goodsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.sku_key
     *
     * @mbggenerated
     */
    private String skuKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.price_mark_key
     *
     * @mbggenerated
     */
    private String priceMarkKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_cart_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.id
     *
     * @return the value of aquatic_cart_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.id
     *
     * @param id the value for aquatic_cart_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.cart_code
     *
     * @return the value of aquatic_cart_info.cart_code
     *
     * @mbggenerated
     */
    public String getCartCode() {
        return cartCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.cart_code
     *
     * @param cartCode the value for aquatic_cart_info.cart_code
     *
     * @mbggenerated
     */
    public void setCartCode(String cartCode) {
        this.cartCode = cartCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.user_key
     *
     * @return the value of aquatic_cart_info.user_key
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.user_key
     *
     * @param userKey the value for aquatic_cart_info.user_key
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.shop_key
     *
     * @return the value of aquatic_cart_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.shop_key
     *
     * @param shopKey the value for aquatic_cart_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.goods_key
     *
     * @return the value of aquatic_cart_info.goods_key
     *
     * @mbggenerated
     */
    public String getGoodsKey() {
        return goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.goods_key
     *
     * @param goodsKey the value for aquatic_cart_info.goods_key
     *
     * @mbggenerated
     */
    public void setGoodsKey(String goodsKey) {
        this.goodsKey = goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.sku_key
     *
     * @return the value of aquatic_cart_info.sku_key
     *
     * @mbggenerated
     */
    public String getSkuKey() {
        return skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.sku_key
     *
     * @param skuKey the value for aquatic_cart_info.sku_key
     *
     * @mbggenerated
     */
    public void setSkuKey(String skuKey) {
        this.skuKey = skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.price_mark_key
     *
     * @return the value of aquatic_cart_info.price_mark_key
     *
     * @mbggenerated
     */
    public String getPriceMarkKey() {
        return priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.price_mark_key
     *
     * @param priceMarkKey the value for aquatic_cart_info.price_mark_key
     *
     * @mbggenerated
     */
    public void setPriceMarkKey(String priceMarkKey) {
        this.priceMarkKey = priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.num
     *
     * @return the value of aquatic_cart_info.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.num
     *
     * @param num the value for aquatic_cart_info.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.add_time
     *
     * @return the value of aquatic_cart_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.add_time
     *
     * @param addTime the value for aquatic_cart_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_cart_info.update_time
     *
     * @return the value of aquatic_cart_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_cart_info.update_time
     *
     * @param updateTime the value for aquatic_cart_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}