package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticRefundCsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.service_key
     *
     * @mbggenerated
     */
    private String serviceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.refund_key
     *
     * @mbggenerated
     */
    private String refundKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.cs_account
     *
     * @mbggenerated
     */
    private String csAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.cs_remark
     *
     * @mbggenerated
     */
    private String csRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_cs_info.cs_addtime
     *
     * @mbggenerated
     */
    private Date csAddtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.id
     *
     * @return the value of aquatic_refund_cs_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.id
     *
     * @param id the value for aquatic_refund_cs_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.service_key
     *
     * @return the value of aquatic_refund_cs_info.service_key
     *
     * @mbggenerated
     */
    public String getServiceKey() {
        return serviceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.service_key
     *
     * @param serviceKey the value for aquatic_refund_cs_info.service_key
     *
     * @mbggenerated
     */
    public void setServiceKey(String serviceKey) {
        this.serviceKey = serviceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.refund_key
     *
     * @return the value of aquatic_refund_cs_info.refund_key
     *
     * @mbggenerated
     */
    public String getRefundKey() {
        return refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.refund_key
     *
     * @param refundKey the value for aquatic_refund_cs_info.refund_key
     *
     * @mbggenerated
     */
    public void setRefundKey(String refundKey) {
        this.refundKey = refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.cs_account
     *
     * @return the value of aquatic_refund_cs_info.cs_account
     *
     * @mbggenerated
     */
    public String getCsAccount() {
        return csAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.cs_account
     *
     * @param csAccount the value for aquatic_refund_cs_info.cs_account
     *
     * @mbggenerated
     */
    public void setCsAccount(String csAccount) {
        this.csAccount = csAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.cs_remark
     *
     * @return the value of aquatic_refund_cs_info.cs_remark
     *
     * @mbggenerated
     */
    public String getCsRemark() {
        return csRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.cs_remark
     *
     * @param csRemark the value for aquatic_refund_cs_info.cs_remark
     *
     * @mbggenerated
     */
    public void setCsRemark(String csRemark) {
        this.csRemark = csRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_cs_info.cs_addtime
     *
     * @return the value of aquatic_refund_cs_info.cs_addtime
     *
     * @mbggenerated
     */
    public Date getCsAddtime() {
        return csAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_cs_info.cs_addtime
     *
     * @param csAddtime the value for aquatic_refund_cs_info.cs_addtime
     *
     * @mbggenerated
     */
    public void setCsAddtime(Date csAddtime) {
        this.csAddtime = csAddtime;
    }
}