package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticUserAddressInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.address_key
     *
     * @mbggenerated
     */
    private String addressKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.user_key
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.is_default
     *
     * @mbggenerated
     */
    private String isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.area
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.street
     *
     * @mbggenerated
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.province_name
     *
     * @mbggenerated
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.city_name
     *
     * @mbggenerated
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.area_name
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_user_address_info.street_name
     *
     * @mbggenerated
     */
    private String streetName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.id
     *
     * @return the value of aquatic_user_address_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.id
     *
     * @param id the value for aquatic_user_address_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.address_key
     *
     * @return the value of aquatic_user_address_info.address_key
     *
     * @mbggenerated
     */
    public String getAddressKey() {
        return addressKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.address_key
     *
     * @param addressKey the value for aquatic_user_address_info.address_key
     *
     * @mbggenerated
     */
    public void setAddressKey(String addressKey) {
        this.addressKey = addressKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.user_key
     *
     * @return the value of aquatic_user_address_info.user_key
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.user_key
     *
     * @param userKey the value for aquatic_user_address_info.user_key
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.address
     *
     * @return the value of aquatic_user_address_info.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.address
     *
     * @param address the value for aquatic_user_address_info.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.telephone
     *
     * @return the value of aquatic_user_address_info.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.telephone
     *
     * @param telephone the value for aquatic_user_address_info.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.code
     *
     * @return the value of aquatic_user_address_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.code
     *
     * @param code the value for aquatic_user_address_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.user_name
     *
     * @return the value of aquatic_user_address_info.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.user_name
     *
     * @param userName the value for aquatic_user_address_info.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.is_default
     *
     * @return the value of aquatic_user_address_info.is_default
     *
     * @mbggenerated
     */
    public String getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.is_default
     *
     * @param isDefault the value for aquatic_user_address_info.is_default
     *
     * @mbggenerated
     */
    public void setIsDefault(String isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.status
     *
     * @return the value of aquatic_user_address_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.status
     *
     * @param status the value for aquatic_user_address_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.add_time
     *
     * @return the value of aquatic_user_address_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.add_time
     *
     * @param addTime the value for aquatic_user_address_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.update_time
     *
     * @return the value of aquatic_user_address_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.update_time
     *
     * @param updateTime the value for aquatic_user_address_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.province
     *
     * @return the value of aquatic_user_address_info.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.province
     *
     * @param province the value for aquatic_user_address_info.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.city
     *
     * @return the value of aquatic_user_address_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.city
     *
     * @param city the value for aquatic_user_address_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.area
     *
     * @return the value of aquatic_user_address_info.area
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.area
     *
     * @param area the value for aquatic_user_address_info.area
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.street
     *
     * @return the value of aquatic_user_address_info.street
     *
     * @mbggenerated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.street
     *
     * @param street the value for aquatic_user_address_info.street
     *
     * @mbggenerated
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.province_name
     *
     * @return the value of aquatic_user_address_info.province_name
     *
     * @mbggenerated
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.province_name
     *
     * @param provinceName the value for aquatic_user_address_info.province_name
     *
     * @mbggenerated
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.city_name
     *
     * @return the value of aquatic_user_address_info.city_name
     *
     * @mbggenerated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.city_name
     *
     * @param cityName the value for aquatic_user_address_info.city_name
     *
     * @mbggenerated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.area_name
     *
     * @return the value of aquatic_user_address_info.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.area_name
     *
     * @param areaName the value for aquatic_user_address_info.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_user_address_info.street_name
     *
     * @return the value of aquatic_user_address_info.street_name
     *
     * @mbggenerated
     */
    public String getStreetName() {
        return streetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_user_address_info.street_name
     *
     * @param streetName the value for aquatic_user_address_info.street_name
     *
     * @mbggenerated
     */
    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }
}