package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticSettleFailOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.settle_key
     *
     * @mbggenerated
     */
    private String settleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.order_money
     *
     * @mbggenerated
     */
    private Long orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.USER_KEY
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.SHOP_KEY
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.order_online
     *
     * @mbggenerated
     */
    private String orderOnline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.staus
     *
     * @mbggenerated
     */
    private String staus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_order.operate_time
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.ID
     *
     * @return the value of aquatic_settle_fail_order.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.ID
     *
     * @param id the value for aquatic_settle_fail_order.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.settle_key
     *
     * @return the value of aquatic_settle_fail_order.settle_key
     *
     * @mbggenerated
     */
    public String getSettleKey() {
        return settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.settle_key
     *
     * @param settleKey the value for aquatic_settle_fail_order.settle_key
     *
     * @mbggenerated
     */
    public void setSettleKey(String settleKey) {
        this.settleKey = settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.order_code
     *
     * @return the value of aquatic_settle_fail_order.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.order_code
     *
     * @param orderCode the value for aquatic_settle_fail_order.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.order_money
     *
     * @return the value of aquatic_settle_fail_order.order_money
     *
     * @mbggenerated
     */
    public Long getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.order_money
     *
     * @param orderMoney the value for aquatic_settle_fail_order.order_money
     *
     * @mbggenerated
     */
    public void setOrderMoney(Long orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.USER_KEY
     *
     * @return the value of aquatic_settle_fail_order.USER_KEY
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.USER_KEY
     *
     * @param userKey the value for aquatic_settle_fail_order.USER_KEY
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.SHOP_KEY
     *
     * @return the value of aquatic_settle_fail_order.SHOP_KEY
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.SHOP_KEY
     *
     * @param shopKey the value for aquatic_settle_fail_order.SHOP_KEY
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.addtime
     *
     * @return the value of aquatic_settle_fail_order.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.addtime
     *
     * @param addtime the value for aquatic_settle_fail_order.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.order_online
     *
     * @return the value of aquatic_settle_fail_order.order_online
     *
     * @mbggenerated
     */
    public String getOrderOnline() {
        return orderOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.order_online
     *
     * @param orderOnline the value for aquatic_settle_fail_order.order_online
     *
     * @mbggenerated
     */
    public void setOrderOnline(String orderOnline) {
        this.orderOnline = orderOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.staus
     *
     * @return the value of aquatic_settle_fail_order.staus
     *
     * @mbggenerated
     */
    public String getStaus() {
        return staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.staus
     *
     * @param staus the value for aquatic_settle_fail_order.staus
     *
     * @mbggenerated
     */
    public void setStaus(String staus) {
        this.staus = staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_order.operate_time
     *
     * @return the value of aquatic_settle_fail_order.operate_time
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_order.operate_time
     *
     * @param operateTime the value for aquatic_settle_fail_order.operate_time
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}