package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticWaitSettleInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.order_money
     *
     * @mbggenerated
     */
    private Long orderMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.userkey
     *
     * @mbggenerated
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.is_lock
     *
     * @mbggenerated
     */
    private String isLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_wait_settle_info.order_online
     *
     * @mbggenerated
     */
    private String orderOnline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.order_code
     *
     * @return the value of aquatic_wait_settle_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.order_code
     *
     * @param orderCode the value for aquatic_wait_settle_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.id
     *
     * @return the value of aquatic_wait_settle_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.id
     *
     * @param id the value for aquatic_wait_settle_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.shop_key
     *
     * @return the value of aquatic_wait_settle_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.shop_key
     *
     * @param shopKey the value for aquatic_wait_settle_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.order_money
     *
     * @return the value of aquatic_wait_settle_info.order_money
     *
     * @mbggenerated
     */
    public Long getOrderMoney() {
        return orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.order_money
     *
     * @param orderMoney the value for aquatic_wait_settle_info.order_money
     *
     * @mbggenerated
     */
    public void setOrderMoney(Long orderMoney) {
        this.orderMoney = orderMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.add_time
     *
     * @return the value of aquatic_wait_settle_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.add_time
     *
     * @param addTime the value for aquatic_wait_settle_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.userkey
     *
     * @return the value of aquatic_wait_settle_info.userkey
     *
     * @mbggenerated
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.userkey
     *
     * @param userkey the value for aquatic_wait_settle_info.userkey
     *
     * @mbggenerated
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.is_lock
     *
     * @return the value of aquatic_wait_settle_info.is_lock
     *
     * @mbggenerated
     */
    public String getIsLock() {
        return isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.is_lock
     *
     * @param isLock the value for aquatic_wait_settle_info.is_lock
     *
     * @mbggenerated
     */
    public void setIsLock(String isLock) {
        this.isLock = isLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_wait_settle_info.order_online
     *
     * @return the value of aquatic_wait_settle_info.order_online
     *
     * @mbggenerated
     */
    public String getOrderOnline() {
        return orderOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_wait_settle_info.order_online
     *
     * @param orderOnline the value for aquatic_wait_settle_info.order_online
     *
     * @mbggenerated
     */
    public void setOrderOnline(String orderOnline) {
        this.orderOnline = orderOnline;
    }
}