package com.haozi.demo.springboot.bean.po;

public class AquaticSettleCardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.settle_key
     *
     * @mbggenerated
     */
    private String settleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.card_key
     *
     * @mbggenerated
     */
    private String cardKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bank_title
     *
     * @mbggenerated
     */
    private String bankTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bank_icon
     *
     * @mbggenerated
     */
    private String bankIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bank_card_no
     *
     * @mbggenerated
     */
    private String bankCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bank_key
     *
     * @mbggenerated
     */
    private String bankKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bind_name
     *
     * @mbggenerated
     */
    private String bindName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bind_card_No
     *
     * @mbggenerated
     */
    private String bindCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_card_info.bind_phone
     *
     * @mbggenerated
     */
    private String bindPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.settle_key
     *
     * @return the value of aquatic_settle_card_info.settle_key
     *
     * @mbggenerated
     */
    public String getSettleKey() {
        return settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.settle_key
     *
     * @param settleKey the value for aquatic_settle_card_info.settle_key
     *
     * @mbggenerated
     */
    public void setSettleKey(String settleKey) {
        this.settleKey = settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.ID
     *
     * @return the value of aquatic_settle_card_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.ID
     *
     * @param id the value for aquatic_settle_card_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.card_key
     *
     * @return the value of aquatic_settle_card_info.card_key
     *
     * @mbggenerated
     */
    public String getCardKey() {
        return cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.card_key
     *
     * @param cardKey the value for aquatic_settle_card_info.card_key
     *
     * @mbggenerated
     */
    public void setCardKey(String cardKey) {
        this.cardKey = cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.shop_key
     *
     * @return the value of aquatic_settle_card_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.shop_key
     *
     * @param shopKey the value for aquatic_settle_card_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bank_title
     *
     * @return the value of aquatic_settle_card_info.bank_title
     *
     * @mbggenerated
     */
    public String getBankTitle() {
        return bankTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bank_title
     *
     * @param bankTitle the value for aquatic_settle_card_info.bank_title
     *
     * @mbggenerated
     */
    public void setBankTitle(String bankTitle) {
        this.bankTitle = bankTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bank_icon
     *
     * @return the value of aquatic_settle_card_info.bank_icon
     *
     * @mbggenerated
     */
    public String getBankIcon() {
        return bankIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bank_icon
     *
     * @param bankIcon the value for aquatic_settle_card_info.bank_icon
     *
     * @mbggenerated
     */
    public void setBankIcon(String bankIcon) {
        this.bankIcon = bankIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bank_card_no
     *
     * @return the value of aquatic_settle_card_info.bank_card_no
     *
     * @mbggenerated
     */
    public String getBankCardNo() {
        return bankCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bank_card_no
     *
     * @param bankCardNo the value for aquatic_settle_card_info.bank_card_no
     *
     * @mbggenerated
     */
    public void setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bank_key
     *
     * @return the value of aquatic_settle_card_info.bank_key
     *
     * @mbggenerated
     */
    public String getBankKey() {
        return bankKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bank_key
     *
     * @param bankKey the value for aquatic_settle_card_info.bank_key
     *
     * @mbggenerated
     */
    public void setBankKey(String bankKey) {
        this.bankKey = bankKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bind_name
     *
     * @return the value of aquatic_settle_card_info.bind_name
     *
     * @mbggenerated
     */
    public String getBindName() {
        return bindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bind_name
     *
     * @param bindName the value for aquatic_settle_card_info.bind_name
     *
     * @mbggenerated
     */
    public void setBindName(String bindName) {
        this.bindName = bindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.province
     *
     * @return the value of aquatic_settle_card_info.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.province
     *
     * @param province the value for aquatic_settle_card_info.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.city
     *
     * @return the value of aquatic_settle_card_info.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.city
     *
     * @param city the value for aquatic_settle_card_info.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bind_card_No
     *
     * @return the value of aquatic_settle_card_info.bind_card_No
     *
     * @mbggenerated
     */
    public String getBindCardNo() {
        return bindCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bind_card_No
     *
     * @param bindCardNo the value for aquatic_settle_card_info.bind_card_No
     *
     * @mbggenerated
     */
    public void setBindCardNo(String bindCardNo) {
        this.bindCardNo = bindCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.card_type
     *
     * @return the value of aquatic_settle_card_info.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.card_type
     *
     * @param cardType the value for aquatic_settle_card_info.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_card_info.bind_phone
     *
     * @return the value of aquatic_settle_card_info.bind_phone
     *
     * @mbggenerated
     */
    public String getBindPhone() {
        return bindPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_card_info.bind_phone
     *
     * @param bindPhone the value for aquatic_settle_card_info.bind_phone
     *
     * @mbggenerated
     */
    public void setBindPhone(String bindPhone) {
        this.bindPhone = bindPhone;
    }
}