package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticCategoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.category_key
     *
     * @mbggenerated
     */
    private String categoryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.sup_category_key
     *
     * @mbggenerated
     */
    private String supCategoryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_category_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.id
     *
     * @return the value of aquatic_category_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.id
     *
     * @param id the value for aquatic_category_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.category_key
     *
     * @return the value of aquatic_category_info.category_key
     *
     * @mbggenerated
     */
    public String getCategoryKey() {
        return categoryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.category_key
     *
     * @param categoryKey the value for aquatic_category_info.category_key
     *
     * @mbggenerated
     */
    public void setCategoryKey(String categoryKey) {
        this.categoryKey = categoryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.category_name
     *
     * @return the value of aquatic_category_info.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.category_name
     *
     * @param categoryName the value for aquatic_category_info.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.sup_category_key
     *
     * @return the value of aquatic_category_info.sup_category_key
     *
     * @mbggenerated
     */
    public String getSupCategoryKey() {
        return supCategoryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.sup_category_key
     *
     * @param supCategoryKey the value for aquatic_category_info.sup_category_key
     *
     * @mbggenerated
     */
    public void setSupCategoryKey(String supCategoryKey) {
        this.supCategoryKey = supCategoryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.status
     *
     * @return the value of aquatic_category_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.status
     *
     * @param status the value for aquatic_category_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.add_time
     *
     * @return the value of aquatic_category_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.add_time
     *
     * @param addTime the value for aquatic_category_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_category_info.update_time
     *
     * @return the value of aquatic_category_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_category_info.update_time
     *
     * @param updateTime the value for aquatic_category_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}