package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticSettleAuditPass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.settle_key
     *
     * @mbggenerated
     */
    private String settleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.SHOP_KEY
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.settle_time
     *
     * @mbggenerated
     */
    private Date settleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.settle_money
     *
     * @mbggenerated
     */
    private Integer settleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.card_key
     *
     * @mbggenerated
     */
    private String cardKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.audit_man
     *
     * @mbggenerated
     */
    private String auditMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.audit_remark
     *
     * @mbggenerated
     */
    private String auditRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.sms_code
     *
     * @mbggenerated
     */
    private String smsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_audit_pass.settle_channel
     *
     * @mbggenerated
     */
    private String settleChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.settle_key
     *
     * @return the value of aquatic_settle_audit_pass.settle_key
     *
     * @mbggenerated
     */
    public String getSettleKey() {
        return settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.settle_key
     *
     * @param settleKey the value for aquatic_settle_audit_pass.settle_key
     *
     * @mbggenerated
     */
    public void setSettleKey(String settleKey) {
        this.settleKey = settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.ID
     *
     * @return the value of aquatic_settle_audit_pass.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.ID
     *
     * @param id the value for aquatic_settle_audit_pass.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.SHOP_KEY
     *
     * @return the value of aquatic_settle_audit_pass.SHOP_KEY
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.SHOP_KEY
     *
     * @param shopKey the value for aquatic_settle_audit_pass.SHOP_KEY
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.settle_time
     *
     * @return the value of aquatic_settle_audit_pass.settle_time
     *
     * @mbggenerated
     */
    public Date getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.settle_time
     *
     * @param settleTime the value for aquatic_settle_audit_pass.settle_time
     *
     * @mbggenerated
     */
    public void setSettleTime(Date settleTime) {
        this.settleTime = settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.settle_money
     *
     * @return the value of aquatic_settle_audit_pass.settle_money
     *
     * @mbggenerated
     */
    public Integer getSettleMoney() {
        return settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.settle_money
     *
     * @param settleMoney the value for aquatic_settle_audit_pass.settle_money
     *
     * @mbggenerated
     */
    public void setSettleMoney(Integer settleMoney) {
        this.settleMoney = settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.card_no
     *
     * @return the value of aquatic_settle_audit_pass.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.card_no
     *
     * @param cardNo the value for aquatic_settle_audit_pass.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.card_key
     *
     * @return the value of aquatic_settle_audit_pass.card_key
     *
     * @mbggenerated
     */
    public String getCardKey() {
        return cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.card_key
     *
     * @param cardKey the value for aquatic_settle_audit_pass.card_key
     *
     * @mbggenerated
     */
    public void setCardKey(String cardKey) {
        this.cardKey = cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.audit_man
     *
     * @return the value of aquatic_settle_audit_pass.audit_man
     *
     * @mbggenerated
     */
    public String getAuditMan() {
        return auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.audit_man
     *
     * @param auditMan the value for aquatic_settle_audit_pass.audit_man
     *
     * @mbggenerated
     */
    public void setAuditMan(String auditMan) {
        this.auditMan = auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.audit_time
     *
     * @return the value of aquatic_settle_audit_pass.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.audit_time
     *
     * @param auditTime the value for aquatic_settle_audit_pass.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.audit_remark
     *
     * @return the value of aquatic_settle_audit_pass.audit_remark
     *
     * @mbggenerated
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.audit_remark
     *
     * @param auditRemark the value for aquatic_settle_audit_pass.audit_remark
     *
     * @mbggenerated
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.sms_code
     *
     * @return the value of aquatic_settle_audit_pass.sms_code
     *
     * @mbggenerated
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.sms_code
     *
     * @param smsCode the value for aquatic_settle_audit_pass.sms_code
     *
     * @mbggenerated
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_audit_pass.settle_channel
     *
     * @return the value of aquatic_settle_audit_pass.settle_channel
     *
     * @mbggenerated
     */
    public String getSettleChannel() {
        return settleChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_audit_pass.settle_channel
     *
     * @param settleChannel the value for aquatic_settle_audit_pass.settle_channel
     *
     * @mbggenerated
     */
    public void setSettleChannel(String settleChannel) {
        this.settleChannel = settleChannel;
    }
}