package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticOrderGoodsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.order_goods_key
     *
     * @mbggenerated
     */
    private String orderGoodsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.goods_key
     *
     * @mbggenerated
     */
    private String goodsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.sku_key
     *
     * @mbggenerated
     */
    private String skuKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.price_mark_key
     *
     * @mbggenerated
     */
    private String priceMarkKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.sales_title
     *
     * @mbggenerated
     */
    private String salesTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.goods_pic
     *
     * @mbggenerated
     */
    private String goodsPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.goods_spec
     *
     * @mbggenerated
     */
    private String goodsSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.current_price
     *
     * @mbggenerated
     */
    private Long currentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.original_price
     *
     * @mbggenerated
     */
    private Long originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.send_address
     *
     * @mbggenerated
     */
    private String sendAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.commission_rate
     *
     * @mbggenerated
     */
    private String commissionRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.commission
     *
     * @mbggenerated
     */
    private Integer commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_order_goods_info.total_money
     *
     * @mbggenerated
     */
    private Long totalMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.id
     *
     * @return the value of aquatic_order_goods_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.id
     *
     * @param id the value for aquatic_order_goods_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.order_goods_key
     *
     * @return the value of aquatic_order_goods_info.order_goods_key
     *
     * @mbggenerated
     */
    public String getOrderGoodsKey() {
        return orderGoodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.order_goods_key
     *
     * @param orderGoodsKey the value for aquatic_order_goods_info.order_goods_key
     *
     * @mbggenerated
     */
    public void setOrderGoodsKey(String orderGoodsKey) {
        this.orderGoodsKey = orderGoodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.order_code
     *
     * @return the value of aquatic_order_goods_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.order_code
     *
     * @param orderCode the value for aquatic_order_goods_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.goods_key
     *
     * @return the value of aquatic_order_goods_info.goods_key
     *
     * @mbggenerated
     */
    public String getGoodsKey() {
        return goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.goods_key
     *
     * @param goodsKey the value for aquatic_order_goods_info.goods_key
     *
     * @mbggenerated
     */
    public void setGoodsKey(String goodsKey) {
        this.goodsKey = goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.sku_key
     *
     * @return the value of aquatic_order_goods_info.sku_key
     *
     * @mbggenerated
     */
    public String getSkuKey() {
        return skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.sku_key
     *
     * @param skuKey the value for aquatic_order_goods_info.sku_key
     *
     * @mbggenerated
     */
    public void setSkuKey(String skuKey) {
        this.skuKey = skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.price_mark_key
     *
     * @return the value of aquatic_order_goods_info.price_mark_key
     *
     * @mbggenerated
     */
    public String getPriceMarkKey() {
        return priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.price_mark_key
     *
     * @param priceMarkKey the value for aquatic_order_goods_info.price_mark_key
     *
     * @mbggenerated
     */
    public void setPriceMarkKey(String priceMarkKey) {
        this.priceMarkKey = priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.sales_title
     *
     * @return the value of aquatic_order_goods_info.sales_title
     *
     * @mbggenerated
     */
    public String getSalesTitle() {
        return salesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.sales_title
     *
     * @param salesTitle the value for aquatic_order_goods_info.sales_title
     *
     * @mbggenerated
     */
    public void setSalesTitle(String salesTitle) {
        this.salesTitle = salesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.goods_name
     *
     * @return the value of aquatic_order_goods_info.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.goods_name
     *
     * @param goodsName the value for aquatic_order_goods_info.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.goods_pic
     *
     * @return the value of aquatic_order_goods_info.goods_pic
     *
     * @mbggenerated
     */
    public String getGoodsPic() {
        return goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.goods_pic
     *
     * @param goodsPic the value for aquatic_order_goods_info.goods_pic
     *
     * @mbggenerated
     */
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.goods_spec
     *
     * @return the value of aquatic_order_goods_info.goods_spec
     *
     * @mbggenerated
     */
    public String getGoodsSpec() {
        return goodsSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.goods_spec
     *
     * @param goodsSpec the value for aquatic_order_goods_info.goods_spec
     *
     * @mbggenerated
     */
    public void setGoodsSpec(String goodsSpec) {
        this.goodsSpec = goodsSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.current_price
     *
     * @return the value of aquatic_order_goods_info.current_price
     *
     * @mbggenerated
     */
    public Long getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.current_price
     *
     * @param currentPrice the value for aquatic_order_goods_info.current_price
     *
     * @mbggenerated
     */
    public void setCurrentPrice(Long currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.original_price
     *
     * @return the value of aquatic_order_goods_info.original_price
     *
     * @mbggenerated
     */
    public Long getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.original_price
     *
     * @param originalPrice the value for aquatic_order_goods_info.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.num
     *
     * @return the value of aquatic_order_goods_info.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.num
     *
     * @param num the value for aquatic_order_goods_info.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.send_address
     *
     * @return the value of aquatic_order_goods_info.send_address
     *
     * @mbggenerated
     */
    public String getSendAddress() {
        return sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.send_address
     *
     * @param sendAddress the value for aquatic_order_goods_info.send_address
     *
     * @mbggenerated
     */
    public void setSendAddress(String sendAddress) {
        this.sendAddress = sendAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.add_time
     *
     * @return the value of aquatic_order_goods_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.add_time
     *
     * @param addTime the value for aquatic_order_goods_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.commission_rate
     *
     * @return the value of aquatic_order_goods_info.commission_rate
     *
     * @mbggenerated
     */
    public String getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.commission_rate
     *
     * @param commissionRate the value for aquatic_order_goods_info.commission_rate
     *
     * @mbggenerated
     */
    public void setCommissionRate(String commissionRate) {
        this.commissionRate = commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.commission
     *
     * @return the value of aquatic_order_goods_info.commission
     *
     * @mbggenerated
     */
    public Integer getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.commission
     *
     * @param commission the value for aquatic_order_goods_info.commission
     *
     * @mbggenerated
     */
    public void setCommission(Integer commission) {
        this.commission = commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_order_goods_info.total_money
     *
     * @return the value of aquatic_order_goods_info.total_money
     *
     * @mbggenerated
     */
    public Long getTotalMoney() {
        return totalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_order_goods_info.total_money
     *
     * @param totalMoney the value for aquatic_order_goods_info.total_money
     *
     * @mbggenerated
     */
    public void setTotalMoney(Long totalMoney) {
        this.totalMoney = totalMoney;
    }
}