package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticRefundApplyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.user_key
     *
     * @mbggenerated
     */
    private String userKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refund_money
     *
     * @mbggenerated
     */
    private Long refundMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refund_status
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.is_receiver
     *
     * @mbggenerated
     */
    private String isReceiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refund_cause
     *
     * @mbggenerated
     */
    private String refundCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refund_explain
     *
     * @mbggenerated
     */
    private String refundExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refuse_explain
     *
     * @mbggenerated
     */
    private String refuseExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.plat_refund_time
     *
     * @mbggenerated
     */
    private Date platRefundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.REFUND_TIME
     *
     * @mbggenerated
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.AGREE_REFUND_TIME
     *
     * @mbggenerated
     */
    private Date agreeRefundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.REFUND_CAUSE_TYPE
     *
     * @mbggenerated
     */
    private String refundCauseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.IS_REFUND_MONEY
     *
     * @mbggenerated
     */
    private String isRefundMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.refund_key
     *
     * @mbggenerated
     */
    private String refundKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.is_arbitra
     *
     * @mbggenerated
     */
    private String isArbitra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.arbitra_context
     *
     * @mbggenerated
     */
    private String arbitraContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.arbitra_time
     *
     * @mbggenerated
     */
    private Date arbitraTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.can_arbitra
     *
     * @mbggenerated
     */
    private String canArbitra;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_refund_apply_info.apply_arbitra_time
     *
     * @mbggenerated
     */
    private Date applyArbitraTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.id
     *
     * @return the value of aquatic_refund_apply_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.id
     *
     * @param id the value for aquatic_refund_apply_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.order_code
     *
     * @return the value of aquatic_refund_apply_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.order_code
     *
     * @param orderCode the value for aquatic_refund_apply_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.user_key
     *
     * @return the value of aquatic_refund_apply_info.user_key
     *
     * @mbggenerated
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.user_key
     *
     * @param userKey the value for aquatic_refund_apply_info.user_key
     *
     * @mbggenerated
     */
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.shop_key
     *
     * @return the value of aquatic_refund_apply_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.shop_key
     *
     * @param shopKey the value for aquatic_refund_apply_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refund_money
     *
     * @return the value of aquatic_refund_apply_info.refund_money
     *
     * @mbggenerated
     */
    public Long getRefundMoney() {
        return refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refund_money
     *
     * @param refundMoney the value for aquatic_refund_apply_info.refund_money
     *
     * @mbggenerated
     */
    public void setRefundMoney(Long refundMoney) {
        this.refundMoney = refundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refund_status
     *
     * @return the value of aquatic_refund_apply_info.refund_status
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refund_status
     *
     * @param refundStatus the value for aquatic_refund_apply_info.refund_status
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.is_receiver
     *
     * @return the value of aquatic_refund_apply_info.is_receiver
     *
     * @mbggenerated
     */
    public String getIsReceiver() {
        return isReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.is_receiver
     *
     * @param isReceiver the value for aquatic_refund_apply_info.is_receiver
     *
     * @mbggenerated
     */
    public void setIsReceiver(String isReceiver) {
        this.isReceiver = isReceiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refund_cause
     *
     * @return the value of aquatic_refund_apply_info.refund_cause
     *
     * @mbggenerated
     */
    public String getRefundCause() {
        return refundCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refund_cause
     *
     * @param refundCause the value for aquatic_refund_apply_info.refund_cause
     *
     * @mbggenerated
     */
    public void setRefundCause(String refundCause) {
        this.refundCause = refundCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refund_explain
     *
     * @return the value of aquatic_refund_apply_info.refund_explain
     *
     * @mbggenerated
     */
    public String getRefundExplain() {
        return refundExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refund_explain
     *
     * @param refundExplain the value for aquatic_refund_apply_info.refund_explain
     *
     * @mbggenerated
     */
    public void setRefundExplain(String refundExplain) {
        this.refundExplain = refundExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refuse_explain
     *
     * @return the value of aquatic_refund_apply_info.refuse_explain
     *
     * @mbggenerated
     */
    public String getRefuseExplain() {
        return refuseExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refuse_explain
     *
     * @param refuseExplain the value for aquatic_refund_apply_info.refuse_explain
     *
     * @mbggenerated
     */
    public void setRefuseExplain(String refuseExplain) {
        this.refuseExplain = refuseExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.plat_refund_time
     *
     * @return the value of aquatic_refund_apply_info.plat_refund_time
     *
     * @mbggenerated
     */
    public Date getPlatRefundTime() {
        return platRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.plat_refund_time
     *
     * @param platRefundTime the value for aquatic_refund_apply_info.plat_refund_time
     *
     * @mbggenerated
     */
    public void setPlatRefundTime(Date platRefundTime) {
        this.platRefundTime = platRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.REFUND_TIME
     *
     * @return the value of aquatic_refund_apply_info.REFUND_TIME
     *
     * @mbggenerated
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.REFUND_TIME
     *
     * @param refundTime the value for aquatic_refund_apply_info.REFUND_TIME
     *
     * @mbggenerated
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.AGREE_REFUND_TIME
     *
     * @return the value of aquatic_refund_apply_info.AGREE_REFUND_TIME
     *
     * @mbggenerated
     */
    public Date getAgreeRefundTime() {
        return agreeRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.AGREE_REFUND_TIME
     *
     * @param agreeRefundTime the value for aquatic_refund_apply_info.AGREE_REFUND_TIME
     *
     * @mbggenerated
     */
    public void setAgreeRefundTime(Date agreeRefundTime) {
        this.agreeRefundTime = agreeRefundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.REFUND_CAUSE_TYPE
     *
     * @return the value of aquatic_refund_apply_info.REFUND_CAUSE_TYPE
     *
     * @mbggenerated
     */
    public String getRefundCauseType() {
        return refundCauseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.REFUND_CAUSE_TYPE
     *
     * @param refundCauseType the value for aquatic_refund_apply_info.REFUND_CAUSE_TYPE
     *
     * @mbggenerated
     */
    public void setRefundCauseType(String refundCauseType) {
        this.refundCauseType = refundCauseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.IS_REFUND_MONEY
     *
     * @return the value of aquatic_refund_apply_info.IS_REFUND_MONEY
     *
     * @mbggenerated
     */
    public String getIsRefundMoney() {
        return isRefundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.IS_REFUND_MONEY
     *
     * @param isRefundMoney the value for aquatic_refund_apply_info.IS_REFUND_MONEY
     *
     * @mbggenerated
     */
    public void setIsRefundMoney(String isRefundMoney) {
        this.isRefundMoney = isRefundMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.status
     *
     * @return the value of aquatic_refund_apply_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.status
     *
     * @param status the value for aquatic_refund_apply_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.refund_key
     *
     * @return the value of aquatic_refund_apply_info.refund_key
     *
     * @mbggenerated
     */
    public String getRefundKey() {
        return refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.refund_key
     *
     * @param refundKey the value for aquatic_refund_apply_info.refund_key
     *
     * @mbggenerated
     */
    public void setRefundKey(String refundKey) {
        this.refundKey = refundKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.is_arbitra
     *
     * @return the value of aquatic_refund_apply_info.is_arbitra
     *
     * @mbggenerated
     */
    public String getIsArbitra() {
        return isArbitra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.is_arbitra
     *
     * @param isArbitra the value for aquatic_refund_apply_info.is_arbitra
     *
     * @mbggenerated
     */
    public void setIsArbitra(String isArbitra) {
        this.isArbitra = isArbitra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.arbitra_context
     *
     * @return the value of aquatic_refund_apply_info.arbitra_context
     *
     * @mbggenerated
     */
    public String getArbitraContext() {
        return arbitraContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.arbitra_context
     *
     * @param arbitraContext the value for aquatic_refund_apply_info.arbitra_context
     *
     * @mbggenerated
     */
    public void setArbitraContext(String arbitraContext) {
        this.arbitraContext = arbitraContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.arbitra_time
     *
     * @return the value of aquatic_refund_apply_info.arbitra_time
     *
     * @mbggenerated
     */
    public Date getArbitraTime() {
        return arbitraTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.arbitra_time
     *
     * @param arbitraTime the value for aquatic_refund_apply_info.arbitra_time
     *
     * @mbggenerated
     */
    public void setArbitraTime(Date arbitraTime) {
        this.arbitraTime = arbitraTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.can_arbitra
     *
     * @return the value of aquatic_refund_apply_info.can_arbitra
     *
     * @mbggenerated
     */
    public String getCanArbitra() {
        return canArbitra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.can_arbitra
     *
     * @param canArbitra the value for aquatic_refund_apply_info.can_arbitra
     *
     * @mbggenerated
     */
    public void setCanArbitra(String canArbitra) {
        this.canArbitra = canArbitra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_refund_apply_info.apply_arbitra_time
     *
     * @return the value of aquatic_refund_apply_info.apply_arbitra_time
     *
     * @mbggenerated
     */
    public Date getApplyArbitraTime() {
        return applyArbitraTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_refund_apply_info.apply_arbitra_time
     *
     * @param applyArbitraTime the value for aquatic_refund_apply_info.apply_arbitra_time
     *
     * @mbggenerated
     */
    public void setApplyArbitraTime(Date applyArbitraTime) {
        this.applyArbitraTime = applyArbitraTime;
    }
}