package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticSettleFailInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.settle_key
     *
     * @mbggenerated
     */
    private String settleKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.SHOP_KEY
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.settle_time
     *
     * @mbggenerated
     */
    private Date settleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.settle_money
     *
     * @mbggenerated
     */
    private Integer settleMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.card_key
     *
     * @mbggenerated
     */
    private String cardKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.audit_man
     *
     * @mbggenerated
     */
    private String auditMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.audit_remark
     *
     * @mbggenerated
     */
    private String auditRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.fail_type
     *
     * @mbggenerated
     */
    private String failType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.staus
     *
     * @mbggenerated
     */
    private String staus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.back_time
     *
     * @mbggenerated
     */
    private Date backTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.back_man
     *
     * @mbggenerated
     */
    private String backMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.back_remark
     *
     * @mbggenerated
     */
    private String backRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.sms_code
     *
     * @mbggenerated
     */
    private String smsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.busi_msg
     *
     * @mbggenerated
     */
    private String busiMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_settle_fail_info.settle_channel
     *
     * @mbggenerated
     */
    private String settleChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.settle_key
     *
     * @return the value of aquatic_settle_fail_info.settle_key
     *
     * @mbggenerated
     */
    public String getSettleKey() {
        return settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.settle_key
     *
     * @param settleKey the value for aquatic_settle_fail_info.settle_key
     *
     * @mbggenerated
     */
    public void setSettleKey(String settleKey) {
        this.settleKey = settleKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.ID
     *
     * @return the value of aquatic_settle_fail_info.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.ID
     *
     * @param id the value for aquatic_settle_fail_info.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.SHOP_KEY
     *
     * @return the value of aquatic_settle_fail_info.SHOP_KEY
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.SHOP_KEY
     *
     * @param shopKey the value for aquatic_settle_fail_info.SHOP_KEY
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.settle_time
     *
     * @return the value of aquatic_settle_fail_info.settle_time
     *
     * @mbggenerated
     */
    public Date getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.settle_time
     *
     * @param settleTime the value for aquatic_settle_fail_info.settle_time
     *
     * @mbggenerated
     */
    public void setSettleTime(Date settleTime) {
        this.settleTime = settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.settle_money
     *
     * @return the value of aquatic_settle_fail_info.settle_money
     *
     * @mbggenerated
     */
    public Integer getSettleMoney() {
        return settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.settle_money
     *
     * @param settleMoney the value for aquatic_settle_fail_info.settle_money
     *
     * @mbggenerated
     */
    public void setSettleMoney(Integer settleMoney) {
        this.settleMoney = settleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.card_no
     *
     * @return the value of aquatic_settle_fail_info.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.card_no
     *
     * @param cardNo the value for aquatic_settle_fail_info.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.card_key
     *
     * @return the value of aquatic_settle_fail_info.card_key
     *
     * @mbggenerated
     */
    public String getCardKey() {
        return cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.card_key
     *
     * @param cardKey the value for aquatic_settle_fail_info.card_key
     *
     * @mbggenerated
     */
    public void setCardKey(String cardKey) {
        this.cardKey = cardKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.audit_man
     *
     * @return the value of aquatic_settle_fail_info.audit_man
     *
     * @mbggenerated
     */
    public String getAuditMan() {
        return auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.audit_man
     *
     * @param auditMan the value for aquatic_settle_fail_info.audit_man
     *
     * @mbggenerated
     */
    public void setAuditMan(String auditMan) {
        this.auditMan = auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.audit_time
     *
     * @return the value of aquatic_settle_fail_info.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.audit_time
     *
     * @param auditTime the value for aquatic_settle_fail_info.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.audit_remark
     *
     * @return the value of aquatic_settle_fail_info.audit_remark
     *
     * @mbggenerated
     */
    public String getAuditRemark() {
        return auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.audit_remark
     *
     * @param auditRemark the value for aquatic_settle_fail_info.audit_remark
     *
     * @mbggenerated
     */
    public void setAuditRemark(String auditRemark) {
        this.auditRemark = auditRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.fail_type
     *
     * @return the value of aquatic_settle_fail_info.fail_type
     *
     * @mbggenerated
     */
    public String getFailType() {
        return failType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.fail_type
     *
     * @param failType the value for aquatic_settle_fail_info.fail_type
     *
     * @mbggenerated
     */
    public void setFailType(String failType) {
        this.failType = failType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.staus
     *
     * @return the value of aquatic_settle_fail_info.staus
     *
     * @mbggenerated
     */
    public String getStaus() {
        return staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.staus
     *
     * @param staus the value for aquatic_settle_fail_info.staus
     *
     * @mbggenerated
     */
    public void setStaus(String staus) {
        this.staus = staus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.back_time
     *
     * @return the value of aquatic_settle_fail_info.back_time
     *
     * @mbggenerated
     */
    public Date getBackTime() {
        return backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.back_time
     *
     * @param backTime the value for aquatic_settle_fail_info.back_time
     *
     * @mbggenerated
     */
    public void setBackTime(Date backTime) {
        this.backTime = backTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.back_man
     *
     * @return the value of aquatic_settle_fail_info.back_man
     *
     * @mbggenerated
     */
    public String getBackMan() {
        return backMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.back_man
     *
     * @param backMan the value for aquatic_settle_fail_info.back_man
     *
     * @mbggenerated
     */
    public void setBackMan(String backMan) {
        this.backMan = backMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.back_remark
     *
     * @return the value of aquatic_settle_fail_info.back_remark
     *
     * @mbggenerated
     */
    public String getBackRemark() {
        return backRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.back_remark
     *
     * @param backRemark the value for aquatic_settle_fail_info.back_remark
     *
     * @mbggenerated
     */
    public void setBackRemark(String backRemark) {
        this.backRemark = backRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.sms_code
     *
     * @return the value of aquatic_settle_fail_info.sms_code
     *
     * @mbggenerated
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.sms_code
     *
     * @param smsCode the value for aquatic_settle_fail_info.sms_code
     *
     * @mbggenerated
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.busi_msg
     *
     * @return the value of aquatic_settle_fail_info.busi_msg
     *
     * @mbggenerated
     */
    public String getBusiMsg() {
        return busiMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.busi_msg
     *
     * @param busiMsg the value for aquatic_settle_fail_info.busi_msg
     *
     * @mbggenerated
     */
    public void setBusiMsg(String busiMsg) {
        this.busiMsg = busiMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_settle_fail_info.settle_channel
     *
     * @return the value of aquatic_settle_fail_info.settle_channel
     *
     * @mbggenerated
     */
    public String getSettleChannel() {
        return settleChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_settle_fail_info.settle_channel
     *
     * @param settleChannel the value for aquatic_settle_fail_info.settle_channel
     *
     * @mbggenerated
     */
    public void setSettleChannel(String settleChannel) {
        this.settleChannel = settleChannel;
    }
}