package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AquaticShopOrderRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.history_money
     *
     * @mbggenerated
     */
    private Long historyMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.addtime
     *
     * @mbggenerated
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_shop_order_record.new_moeny
     *
     * @mbggenerated
     */
    private Long newMoeny;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.id
     *
     * @return the value of aquatic_shop_order_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.id
     *
     * @param id the value for aquatic_shop_order_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.order_code
     *
     * @return the value of aquatic_shop_order_record.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.order_code
     *
     * @param orderCode the value for aquatic_shop_order_record.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.shop_key
     *
     * @return the value of aquatic_shop_order_record.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.shop_key
     *
     * @param shopKey the value for aquatic_shop_order_record.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.history_money
     *
     * @return the value of aquatic_shop_order_record.history_money
     *
     * @mbggenerated
     */
    public Long getHistoryMoney() {
        return historyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.history_money
     *
     * @param historyMoney the value for aquatic_shop_order_record.history_money
     *
     * @mbggenerated
     */
    public void setHistoryMoney(Long historyMoney) {
        this.historyMoney = historyMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.addtime
     *
     * @return the value of aquatic_shop_order_record.addtime
     *
     * @mbggenerated
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.addtime
     *
     * @param addtime the value for aquatic_shop_order_record.addtime
     *
     * @mbggenerated
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_shop_order_record.new_moeny
     *
     * @return the value of aquatic_shop_order_record.new_moeny
     *
     * @mbggenerated
     */
    public Long getNewMoeny() {
        return newMoeny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_shop_order_record.new_moeny
     *
     * @param newMoeny the value for aquatic_shop_order_record.new_moeny
     *
     * @mbggenerated
     */
    public void setNewMoeny(Long newMoeny) {
        this.newMoeny = newMoeny;
    }
}