package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class AuqaticTransferInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.transfer_code
     *
     * @mbggenerated
     */
    private String transferCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.busi_key
     *
     * @mbggenerated
     */
    private String busiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.transfer_type
     *
     * @mbggenerated
     */
    private String transferType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.trade_query_code
     *
     * @mbggenerated
     */
    private String tradeQueryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.next_transfer_code
     *
     * @mbggenerated
     */
    private String nextTransferCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.from_account_code
     *
     * @mbggenerated
     */
    private String fromAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.to_account_code
     *
     * @mbggenerated
     */
    private String toAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.amount
     *
     * @mbggenerated
     */
    private String amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.transfer_status
     *
     * @mbggenerated
     */
    private String transferStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.rollback_status
     *
     * @mbggenerated
     */
    private String rollbackStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auqatic_transfer_info.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.id
     *
     * @return the value of auqatic_transfer_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.id
     *
     * @param id the value for auqatic_transfer_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.transfer_code
     *
     * @return the value of auqatic_transfer_info.transfer_code
     *
     * @mbggenerated
     */
    public String getTransferCode() {
        return transferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.transfer_code
     *
     * @param transferCode the value for auqatic_transfer_info.transfer_code
     *
     * @mbggenerated
     */
    public void setTransferCode(String transferCode) {
        this.transferCode = transferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.busi_key
     *
     * @return the value of auqatic_transfer_info.busi_key
     *
     * @mbggenerated
     */
    public String getBusiKey() {
        return busiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.busi_key
     *
     * @param busiKey the value for auqatic_transfer_info.busi_key
     *
     * @mbggenerated
     */
    public void setBusiKey(String busiKey) {
        this.busiKey = busiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.transfer_type
     *
     * @return the value of auqatic_transfer_info.transfer_type
     *
     * @mbggenerated
     */
    public String getTransferType() {
        return transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.transfer_type
     *
     * @param transferType the value for auqatic_transfer_info.transfer_type
     *
     * @mbggenerated
     */
    public void setTransferType(String transferType) {
        this.transferType = transferType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.trade_query_code
     *
     * @return the value of auqatic_transfer_info.trade_query_code
     *
     * @mbggenerated
     */
    public String getTradeQueryCode() {
        return tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.trade_query_code
     *
     * @param tradeQueryCode the value for auqatic_transfer_info.trade_query_code
     *
     * @mbggenerated
     */
    public void setTradeQueryCode(String tradeQueryCode) {
        this.tradeQueryCode = tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.next_transfer_code
     *
     * @return the value of auqatic_transfer_info.next_transfer_code
     *
     * @mbggenerated
     */
    public String getNextTransferCode() {
        return nextTransferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.next_transfer_code
     *
     * @param nextTransferCode the value for auqatic_transfer_info.next_transfer_code
     *
     * @mbggenerated
     */
    public void setNextTransferCode(String nextTransferCode) {
        this.nextTransferCode = nextTransferCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.from_account_code
     *
     * @return the value of auqatic_transfer_info.from_account_code
     *
     * @mbggenerated
     */
    public String getFromAccountCode() {
        return fromAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.from_account_code
     *
     * @param fromAccountCode the value for auqatic_transfer_info.from_account_code
     *
     * @mbggenerated
     */
    public void setFromAccountCode(String fromAccountCode) {
        this.fromAccountCode = fromAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.to_account_code
     *
     * @return the value of auqatic_transfer_info.to_account_code
     *
     * @mbggenerated
     */
    public String getToAccountCode() {
        return toAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.to_account_code
     *
     * @param toAccountCode the value for auqatic_transfer_info.to_account_code
     *
     * @mbggenerated
     */
    public void setToAccountCode(String toAccountCode) {
        this.toAccountCode = toAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.amount
     *
     * @return the value of auqatic_transfer_info.amount
     *
     * @mbggenerated
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.amount
     *
     * @param amount the value for auqatic_transfer_info.amount
     *
     * @mbggenerated
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.transfer_status
     *
     * @return the value of auqatic_transfer_info.transfer_status
     *
     * @mbggenerated
     */
    public String getTransferStatus() {
        return transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.transfer_status
     *
     * @param transferStatus the value for auqatic_transfer_info.transfer_status
     *
     * @mbggenerated
     */
    public void setTransferStatus(String transferStatus) {
        this.transferStatus = transferStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.rollback_status
     *
     * @return the value of auqatic_transfer_info.rollback_status
     *
     * @mbggenerated
     */
    public String getRollbackStatus() {
        return rollbackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.rollback_status
     *
     * @param rollbackStatus the value for auqatic_transfer_info.rollback_status
     *
     * @mbggenerated
     */
    public void setRollbackStatus(String rollbackStatus) {
        this.rollbackStatus = rollbackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.add_time
     *
     * @return the value of auqatic_transfer_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.add_time
     *
     * @param addTime the value for auqatic_transfer_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auqatic_transfer_info.end_time
     *
     * @return the value of auqatic_transfer_info.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auqatic_transfer_info.end_time
     *
     * @param endTime the value for auqatic_transfer_info.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}