package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class BankAccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_code
     *
     * @mbggenerated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_type
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_no
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.parent_account_code
     *
     * @mbggenerated
     */
    private String parentAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.bank_code
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.bank_name
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.cust_type
     *
     * @mbggenerated
     */
    private Integer custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.account_explain
     *
     * @mbggenerated
     */
    private String accountExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bank_account_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_id
     *
     * @return the value of bank_account_info.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_id
     *
     * @param accountId the value for bank_account_info.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_code
     *
     * @return the value of bank_account_info.account_code
     *
     * @mbggenerated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_code
     *
     * @param accountCode the value for bank_account_info.account_code
     *
     * @mbggenerated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_type
     *
     * @return the value of bank_account_info.account_type
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_type
     *
     * @param accountType the value for bank_account_info.account_type
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_no
     *
     * @return the value of bank_account_info.account_no
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_no
     *
     * @param accountNo the value for bank_account_info.account_no
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.parent_account_code
     *
     * @return the value of bank_account_info.parent_account_code
     *
     * @mbggenerated
     */
    public String getParentAccountCode() {
        return parentAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.parent_account_code
     *
     * @param parentAccountCode the value for bank_account_info.parent_account_code
     *
     * @mbggenerated
     */
    public void setParentAccountCode(String parentAccountCode) {
        this.parentAccountCode = parentAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_name
     *
     * @return the value of bank_account_info.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_name
     *
     * @param accountName the value for bank_account_info.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.bank_code
     *
     * @return the value of bank_account_info.bank_code
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.bank_code
     *
     * @param bankCode the value for bank_account_info.bank_code
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.bank_name
     *
     * @return the value of bank_account_info.bank_name
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.bank_name
     *
     * @param bankName the value for bank_account_info.bank_name
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.cust_type
     *
     * @return the value of bank_account_info.cust_type
     *
     * @mbggenerated
     */
    public Integer getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.cust_type
     *
     * @param custType the value for bank_account_info.cust_type
     *
     * @mbggenerated
     */
    public void setCustType(Integer custType) {
        this.custType = custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.account_explain
     *
     * @return the value of bank_account_info.account_explain
     *
     * @mbggenerated
     */
    public String getAccountExplain() {
        return accountExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.account_explain
     *
     * @param accountExplain the value for bank_account_info.account_explain
     *
     * @mbggenerated
     */
    public void setAccountExplain(String accountExplain) {
        this.accountExplain = accountExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bank_account_info.add_time
     *
     * @return the value of bank_account_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bank_account_info.add_time
     *
     * @param addTime the value for bank_account_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}