package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class CmbcTransferRecod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.cmbc_id
     *
     * @mbggenerated
     */
    private Integer cmbcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.trade_query_code
     *
     * @mbggenerated
     */
    private String tradeQueryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.amount_type
     *
     * @mbggenerated
     */
    private String amountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.trnId
     *
     * @mbggenerated
     */
    private String trnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.cltcookie
     *
     * @mbggenerated
     */
    private String cltcookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.insId
     *
     * @mbggenerated
     */
    private String insid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.acntNo
     *
     * @mbggenerated
     */
    private String acntno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.acntName
     *
     * @mbggenerated
     */
    private String acntname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.acntToNo
     *
     * @mbggenerated
     */
    private String acnttono;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.acntToName
     *
     * @mbggenerated
     */
    private String acnttoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.externBank
     *
     * @mbggenerated
     */
    private Integer externbank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.localFlag
     *
     * @mbggenerated
     */
    private Integer localflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.rcvCustType
     *
     * @mbggenerated
     */
    private Integer rcvcusttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.bankCode
     *
     * @mbggenerated
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.bankName
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.bankAddr
     *
     * @mbggenerated
     */
    private String bankaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.areaCode
     *
     * @mbggenerated
     */
    private String areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.transfer_explain
     *
     * @mbggenerated
     */
    private String transferExplain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.transfer_result
     *
     * @mbggenerated
     */
    private Integer transferResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.svrId
     *
     * @mbggenerated
     */
    private String svrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.balance
     *
     * @mbggenerated
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.severity
     *
     * @mbggenerated
     */
    private String severity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.message
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.dtServer
     *
     * @mbggenerated
     */
    private Date dtserver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.userKey
     *
     * @mbggenerated
     */
    private String userkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_transfer_recod.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.cmbc_id
     *
     * @return the value of cmbc_transfer_recod.cmbc_id
     *
     * @mbggenerated
     */
    public Integer getCmbcId() {
        return cmbcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.cmbc_id
     *
     * @param cmbcId the value for cmbc_transfer_recod.cmbc_id
     *
     * @mbggenerated
     */
    public void setCmbcId(Integer cmbcId) {
        this.cmbcId = cmbcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.trade_query_code
     *
     * @return the value of cmbc_transfer_recod.trade_query_code
     *
     * @mbggenerated
     */
    public String getTradeQueryCode() {
        return tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.trade_query_code
     *
     * @param tradeQueryCode the value for cmbc_transfer_recod.trade_query_code
     *
     * @mbggenerated
     */
    public void setTradeQueryCode(String tradeQueryCode) {
        this.tradeQueryCode = tradeQueryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.amount_type
     *
     * @return the value of cmbc_transfer_recod.amount_type
     *
     * @mbggenerated
     */
    public String getAmountType() {
        return amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.amount_type
     *
     * @param amountType the value for cmbc_transfer_recod.amount_type
     *
     * @mbggenerated
     */
    public void setAmountType(String amountType) {
        this.amountType = amountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.trnId
     *
     * @return the value of cmbc_transfer_recod.trnId
     *
     * @mbggenerated
     */
    public String getTrnid() {
        return trnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.trnId
     *
     * @param trnid the value for cmbc_transfer_recod.trnId
     *
     * @mbggenerated
     */
    public void setTrnid(String trnid) {
        this.trnid = trnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.cltcookie
     *
     * @return the value of cmbc_transfer_recod.cltcookie
     *
     * @mbggenerated
     */
    public String getCltcookie() {
        return cltcookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.cltcookie
     *
     * @param cltcookie the value for cmbc_transfer_recod.cltcookie
     *
     * @mbggenerated
     */
    public void setCltcookie(String cltcookie) {
        this.cltcookie = cltcookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.insId
     *
     * @return the value of cmbc_transfer_recod.insId
     *
     * @mbggenerated
     */
    public String getInsid() {
        return insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.insId
     *
     * @param insid the value for cmbc_transfer_recod.insId
     *
     * @mbggenerated
     */
    public void setInsid(String insid) {
        this.insid = insid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.acntNo
     *
     * @return the value of cmbc_transfer_recod.acntNo
     *
     * @mbggenerated
     */
    public String getAcntno() {
        return acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.acntNo
     *
     * @param acntno the value for cmbc_transfer_recod.acntNo
     *
     * @mbggenerated
     */
    public void setAcntno(String acntno) {
        this.acntno = acntno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.acntName
     *
     * @return the value of cmbc_transfer_recod.acntName
     *
     * @mbggenerated
     */
    public String getAcntname() {
        return acntname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.acntName
     *
     * @param acntname the value for cmbc_transfer_recod.acntName
     *
     * @mbggenerated
     */
    public void setAcntname(String acntname) {
        this.acntname = acntname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.acntToNo
     *
     * @return the value of cmbc_transfer_recod.acntToNo
     *
     * @mbggenerated
     */
    public String getAcnttono() {
        return acnttono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.acntToNo
     *
     * @param acnttono the value for cmbc_transfer_recod.acntToNo
     *
     * @mbggenerated
     */
    public void setAcnttono(String acnttono) {
        this.acnttono = acnttono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.acntToName
     *
     * @return the value of cmbc_transfer_recod.acntToName
     *
     * @mbggenerated
     */
    public String getAcnttoname() {
        return acnttoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.acntToName
     *
     * @param acnttoname the value for cmbc_transfer_recod.acntToName
     *
     * @mbggenerated
     */
    public void setAcnttoname(String acnttoname) {
        this.acnttoname = acnttoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.externBank
     *
     * @return the value of cmbc_transfer_recod.externBank
     *
     * @mbggenerated
     */
    public Integer getExternbank() {
        return externbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.externBank
     *
     * @param externbank the value for cmbc_transfer_recod.externBank
     *
     * @mbggenerated
     */
    public void setExternbank(Integer externbank) {
        this.externbank = externbank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.localFlag
     *
     * @return the value of cmbc_transfer_recod.localFlag
     *
     * @mbggenerated
     */
    public Integer getLocalflag() {
        return localflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.localFlag
     *
     * @param localflag the value for cmbc_transfer_recod.localFlag
     *
     * @mbggenerated
     */
    public void setLocalflag(Integer localflag) {
        this.localflag = localflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.rcvCustType
     *
     * @return the value of cmbc_transfer_recod.rcvCustType
     *
     * @mbggenerated
     */
    public Integer getRcvcusttype() {
        return rcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.rcvCustType
     *
     * @param rcvcusttype the value for cmbc_transfer_recod.rcvCustType
     *
     * @mbggenerated
     */
    public void setRcvcusttype(Integer rcvcusttype) {
        this.rcvcusttype = rcvcusttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.bankCode
     *
     * @return the value of cmbc_transfer_recod.bankCode
     *
     * @mbggenerated
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.bankCode
     *
     * @param bankcode the value for cmbc_transfer_recod.bankCode
     *
     * @mbggenerated
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.bankName
     *
     * @return the value of cmbc_transfer_recod.bankName
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.bankName
     *
     * @param bankname the value for cmbc_transfer_recod.bankName
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.bankAddr
     *
     * @return the value of cmbc_transfer_recod.bankAddr
     *
     * @mbggenerated
     */
    public String getBankaddr() {
        return bankaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.bankAddr
     *
     * @param bankaddr the value for cmbc_transfer_recod.bankAddr
     *
     * @mbggenerated
     */
    public void setBankaddr(String bankaddr) {
        this.bankaddr = bankaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.areaCode
     *
     * @return the value of cmbc_transfer_recod.areaCode
     *
     * @mbggenerated
     */
    public String getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.areaCode
     *
     * @param areacode the value for cmbc_transfer_recod.areaCode
     *
     * @mbggenerated
     */
    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.amount
     *
     * @return the value of cmbc_transfer_recod.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.amount
     *
     * @param amount the value for cmbc_transfer_recod.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.transfer_explain
     *
     * @return the value of cmbc_transfer_recod.transfer_explain
     *
     * @mbggenerated
     */
    public String getTransferExplain() {
        return transferExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.transfer_explain
     *
     * @param transferExplain the value for cmbc_transfer_recod.transfer_explain
     *
     * @mbggenerated
     */
    public void setTransferExplain(String transferExplain) {
        this.transferExplain = transferExplain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.transfer_result
     *
     * @return the value of cmbc_transfer_recod.transfer_result
     *
     * @mbggenerated
     */
    public Integer getTransferResult() {
        return transferResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.transfer_result
     *
     * @param transferResult the value for cmbc_transfer_recod.transfer_result
     *
     * @mbggenerated
     */
    public void setTransferResult(Integer transferResult) {
        this.transferResult = transferResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.svrId
     *
     * @return the value of cmbc_transfer_recod.svrId
     *
     * @mbggenerated
     */
    public String getSvrid() {
        return svrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.svrId
     *
     * @param svrid the value for cmbc_transfer_recod.svrId
     *
     * @mbggenerated
     */
    public void setSvrid(String svrid) {
        this.svrid = svrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.balance
     *
     * @return the value of cmbc_transfer_recod.balance
     *
     * @mbggenerated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.balance
     *
     * @param balance the value for cmbc_transfer_recod.balance
     *
     * @mbggenerated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.code
     *
     * @return the value of cmbc_transfer_recod.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.code
     *
     * @param code the value for cmbc_transfer_recod.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.severity
     *
     * @return the value of cmbc_transfer_recod.severity
     *
     * @mbggenerated
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.severity
     *
     * @param severity the value for cmbc_transfer_recod.severity
     *
     * @mbggenerated
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.message
     *
     * @return the value of cmbc_transfer_recod.message
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.message
     *
     * @param message the value for cmbc_transfer_recod.message
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.dtServer
     *
     * @return the value of cmbc_transfer_recod.dtServer
     *
     * @mbggenerated
     */
    public Date getDtserver() {
        return dtserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.dtServer
     *
     * @param dtserver the value for cmbc_transfer_recod.dtServer
     *
     * @mbggenerated
     */
    public void setDtserver(Date dtserver) {
        this.dtserver = dtserver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.userKey
     *
     * @return the value of cmbc_transfer_recod.userKey
     *
     * @mbggenerated
     */
    public String getUserkey() {
        return userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.userKey
     *
     * @param userkey the value for cmbc_transfer_recod.userKey
     *
     * @mbggenerated
     */
    public void setUserkey(String userkey) {
        this.userkey = userkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_transfer_recod.add_time
     *
     * @return the value of cmbc_transfer_recod.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_transfer_recod.add_time
     *
     * @param addTime the value for cmbc_transfer_recod.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}