package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class CmbcAccountRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.account_id
     *
     * @mbggenerated
     */
    private Integer accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.account_code
     *
     * @mbggenerated
     */
    private String accountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.clientId
     *
     * @mbggenerated
     */
    private String clientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.userId
     *
     * @mbggenerated
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.userPswd
     *
     * @mbggenerated
     */
    private String userpswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmbc_account_relation.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.account_id
     *
     * @return the value of cmbc_account_relation.account_id
     *
     * @mbggenerated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.account_id
     *
     * @param accountId the value for cmbc_account_relation.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.account_code
     *
     * @return the value of cmbc_account_relation.account_code
     *
     * @mbggenerated
     */
    public String getAccountCode() {
        return accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.account_code
     *
     * @param accountCode the value for cmbc_account_relation.account_code
     *
     * @mbggenerated
     */
    public void setAccountCode(String accountCode) {
        this.accountCode = accountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.clientId
     *
     * @return the value of cmbc_account_relation.clientId
     *
     * @mbggenerated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.clientId
     *
     * @param clientid the value for cmbc_account_relation.clientId
     *
     * @mbggenerated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.userId
     *
     * @return the value of cmbc_account_relation.userId
     *
     * @mbggenerated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.userId
     *
     * @param userid the value for cmbc_account_relation.userId
     *
     * @mbggenerated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.userPswd
     *
     * @return the value of cmbc_account_relation.userPswd
     *
     * @mbggenerated
     */
    public String getUserpswd() {
        return userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.userPswd
     *
     * @param userpswd the value for cmbc_account_relation.userPswd
     *
     * @mbggenerated
     */
    public void setUserpswd(String userpswd) {
        this.userpswd = userpswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmbc_account_relation.add_time
     *
     * @return the value of cmbc_account_relation.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmbc_account_relation.add_time
     *
     * @param addTime the value for cmbc_account_relation.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}