package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class EndOrderRateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.choose_type
     *
     * @mbggenerated
     */
    private String chooseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    private String feeIsPlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    private String loaningIsPlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    private Long baseFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    private Long appendFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.audit_man
     *
     * @mbggenerated
     */
    private String auditMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column end_order_rate_info.audit_time
     *
     * @mbggenerated
     */
    private Date auditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.id
     *
     * @return the value of end_order_rate_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.id
     *
     * @param id the value for end_order_rate_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.order_code
     *
     * @return the value of end_order_rate_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.order_code
     *
     * @param orderCode the value for end_order_rate_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.card_type
     *
     * @return the value of end_order_rate_info.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.card_type
     *
     * @param cardType the value for end_order_rate_info.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.total_fee
     *
     * @return the value of end_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.total_fee
     *
     * @param totalFee the value for end_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.choose_type
     *
     * @return the value of end_order_rate_info.choose_type
     *
     * @mbggenerated
     */
    public String getChooseType() {
        return chooseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.choose_type
     *
     * @param chooseType the value for end_order_rate_info.choose_type
     *
     * @mbggenerated
     */
    public void setChooseType(String chooseType) {
        this.chooseType = chooseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.fee_is_plat
     *
     * @return the value of end_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    public String getFeeIsPlat() {
        return feeIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.fee_is_plat
     *
     * @param feeIsPlat the value for end_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    public void setFeeIsPlat(String feeIsPlat) {
        this.feeIsPlat = feeIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.loaning_is_plat
     *
     * @return the value of end_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    public String getLoaningIsPlat() {
        return loaningIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.loaning_is_plat
     *
     * @param loaningIsPlat the value for end_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    public void setLoaningIsPlat(String loaningIsPlat) {
        this.loaningIsPlat = loaningIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.add_time
     *
     * @return the value of end_order_rate_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.add_time
     *
     * @param addTime the value for end_order_rate_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.base_fee
     *
     * @return the value of end_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    public Long getBaseFee() {
        return baseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.base_fee
     *
     * @param baseFee the value for end_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    public void setBaseFee(Long baseFee) {
        this.baseFee = baseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.append_fee
     *
     * @return the value of end_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    public Long getAppendFee() {
        return appendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.append_fee
     *
     * @param appendFee the value for end_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    public void setAppendFee(Long appendFee) {
        this.appendFee = appendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.audit_man
     *
     * @return the value of end_order_rate_info.audit_man
     *
     * @mbggenerated
     */
    public String getAuditMan() {
        return auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.audit_man
     *
     * @param auditMan the value for end_order_rate_info.audit_man
     *
     * @mbggenerated
     */
    public void setAuditMan(String auditMan) {
        this.auditMan = auditMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column end_order_rate_info.audit_time
     *
     * @return the value of end_order_rate_info.audit_time
     *
     * @mbggenerated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column end_order_rate_info.audit_time
     *
     * @param auditTime the value for end_order_rate_info.audit_time
     *
     * @mbggenerated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }
}