package com.haozi.demo.springboot.bean.po;

import java.util.Date;

public class PlatOrderRateInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.order_code
     *
     * @mbggenerated
     */
    private String orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.card_type
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    private Long baseFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    private Long appendFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.pos_type
     *
     * @mbggenerated
     */
    private String posType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.fee_rate
     *
     * @mbggenerated
     */
    private Long feeRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.loaning_rate
     *
     * @mbggenerated
     */
    private Long loaningRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    private String feeIsPlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    private String loaningIsPlat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.dianzi_fee
     *
     * @mbggenerated
     */
    private Long dianziFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.settle_amount
     *
     * @mbggenerated
     */
    private Long settleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plat_order_rate_info.remit_amount
     *
     * @mbggenerated
     */
    private Long remitAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.order_code
     *
     * @return the value of plat_order_rate_info.order_code
     *
     * @mbggenerated
     */
    public String getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.order_code
     *
     * @param orderCode the value for plat_order_rate_info.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(String orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.shop_key
     *
     * @return the value of plat_order_rate_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.shop_key
     *
     * @param shopKey the value for plat_order_rate_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.card_type
     *
     * @return the value of plat_order_rate_info.card_type
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.card_type
     *
     * @param cardType the value for plat_order_rate_info.card_type
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.base_fee
     *
     * @return the value of plat_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    public Long getBaseFee() {
        return baseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.base_fee
     *
     * @param baseFee the value for plat_order_rate_info.base_fee
     *
     * @mbggenerated
     */
    public void setBaseFee(Long baseFee) {
        this.baseFee = baseFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.append_fee
     *
     * @return the value of plat_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    public Long getAppendFee() {
        return appendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.append_fee
     *
     * @param appendFee the value for plat_order_rate_info.append_fee
     *
     * @mbggenerated
     */
    public void setAppendFee(Long appendFee) {
        this.appendFee = appendFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.total_fee
     *
     * @return the value of plat_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.total_fee
     *
     * @param totalFee the value for plat_order_rate_info.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.pos_type
     *
     * @return the value of plat_order_rate_info.pos_type
     *
     * @mbggenerated
     */
    public String getPosType() {
        return posType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.pos_type
     *
     * @param posType the value for plat_order_rate_info.pos_type
     *
     * @mbggenerated
     */
    public void setPosType(String posType) {
        this.posType = posType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.fee_rate
     *
     * @return the value of plat_order_rate_info.fee_rate
     *
     * @mbggenerated
     */
    public Long getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.fee_rate
     *
     * @param feeRate the value for plat_order_rate_info.fee_rate
     *
     * @mbggenerated
     */
    public void setFeeRate(Long feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.loaning_rate
     *
     * @return the value of plat_order_rate_info.loaning_rate
     *
     * @mbggenerated
     */
    public Long getLoaningRate() {
        return loaningRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.loaning_rate
     *
     * @param loaningRate the value for plat_order_rate_info.loaning_rate
     *
     * @mbggenerated
     */
    public void setLoaningRate(Long loaningRate) {
        this.loaningRate = loaningRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.fee_is_plat
     *
     * @return the value of plat_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    public String getFeeIsPlat() {
        return feeIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.fee_is_plat
     *
     * @param feeIsPlat the value for plat_order_rate_info.fee_is_plat
     *
     * @mbggenerated
     */
    public void setFeeIsPlat(String feeIsPlat) {
        this.feeIsPlat = feeIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.loaning_is_plat
     *
     * @return the value of plat_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    public String getLoaningIsPlat() {
        return loaningIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.loaning_is_plat
     *
     * @param loaningIsPlat the value for plat_order_rate_info.loaning_is_plat
     *
     * @mbggenerated
     */
    public void setLoaningIsPlat(String loaningIsPlat) {
        this.loaningIsPlat = loaningIsPlat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.add_time
     *
     * @return the value of plat_order_rate_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.add_time
     *
     * @param addTime the value for plat_order_rate_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.dianzi_fee
     *
     * @return the value of plat_order_rate_info.dianzi_fee
     *
     * @mbggenerated
     */
    public Long getDianziFee() {
        return dianziFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.dianzi_fee
     *
     * @param dianziFee the value for plat_order_rate_info.dianzi_fee
     *
     * @mbggenerated
     */
    public void setDianziFee(Long dianziFee) {
        this.dianziFee = dianziFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.settle_amount
     *
     * @return the value of plat_order_rate_info.settle_amount
     *
     * @mbggenerated
     */
    public Long getSettleAmount() {
        return settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.settle_amount
     *
     * @param settleAmount the value for plat_order_rate_info.settle_amount
     *
     * @mbggenerated
     */
    public void setSettleAmount(Long settleAmount) {
        this.settleAmount = settleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plat_order_rate_info.remit_amount
     *
     * @return the value of plat_order_rate_info.remit_amount
     *
     * @mbggenerated
     */
    public Long getRemitAmount() {
        return remitAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plat_order_rate_info.remit_amount
     *
     * @param remitAmount the value for plat_order_rate_info.remit_amount
     *
     * @mbggenerated
     */
    public void setRemitAmount(Long remitAmount) {
        this.remitAmount = remitAmount;
    }
}