package com.haozi.demo.springboot.bean.po;

public class QrtzSchedulerStateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated
     */
    private String instanceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @return the value of qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.SCHED_NAME
     *
     * @param schedName the value for qrtz_scheduler_state.SCHED_NAME
     *
     * @mbggenerated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @return the value of qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_scheduler_state.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }
}