package com.haozi.demo.springboot.bean.po;

public class QrtzFiredTriggers extends QrtzFiredTriggersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbggenerated
     */
    private String triggerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    private String triggerGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbggenerated
     */
    private String instanceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @mbggenerated
     */
    private Long firedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @mbggenerated
     */
    private Long schedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.PRIORITY
     *
     * @mbggenerated
     */
    private Integer priority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.STATE
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_NAME
     *
     * @mbggenerated
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @mbggenerated
     */
    private String jobGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    private String requestsRecovery;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @return the value of qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbggenerated
     */
    public String getTriggerName() {
        return triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.TRIGGER_NAME
     *
     * @param triggerName the value for qrtz_fired_triggers.TRIGGER_NAME
     *
     * @mbggenerated
     */
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @return the value of qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_fired_triggers.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @return the value of qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.INSTANCE_NAME
     *
     * @param instanceName the value for qrtz_fired_triggers.INSTANCE_NAME
     *
     * @mbggenerated
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @return the value of qrtz_fired_triggers.FIRED_TIME
     *
     * @mbggenerated
     */
    public Long getFiredTime() {
        return firedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.FIRED_TIME
     *
     * @param firedTime the value for qrtz_fired_triggers.FIRED_TIME
     *
     * @mbggenerated
     */
    public void setFiredTime(Long firedTime) {
        this.firedTime = firedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @return the value of qrtz_fired_triggers.SCHED_TIME
     *
     * @mbggenerated
     */
    public Long getSchedTime() {
        return schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.SCHED_TIME
     *
     * @param schedTime the value for qrtz_fired_triggers.SCHED_TIME
     *
     * @mbggenerated
     */
    public void setSchedTime(Long schedTime) {
        this.schedTime = schedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.PRIORITY
     *
     * @return the value of qrtz_fired_triggers.PRIORITY
     *
     * @mbggenerated
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.PRIORITY
     *
     * @param priority the value for qrtz_fired_triggers.PRIORITY
     *
     * @mbggenerated
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.STATE
     *
     * @return the value of qrtz_fired_triggers.STATE
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.STATE
     *
     * @param state the value for qrtz_fired_triggers.STATE
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.JOB_NAME
     *
     * @return the value of qrtz_fired_triggers.JOB_NAME
     *
     * @mbggenerated
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.JOB_NAME
     *
     * @param jobName the value for qrtz_fired_triggers.JOB_NAME
     *
     * @mbggenerated
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @return the value of qrtz_fired_triggers.JOB_GROUP
     *
     * @mbggenerated
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.JOB_GROUP
     *
     * @param jobGroup the value for qrtz_fired_triggers.JOB_GROUP
     *
     * @mbggenerated
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @return the value of qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_fired_triggers.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_fired_triggers.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }
}