package com.haozi.demo.springboot.bean.po;

public class QrtzPausedTriggerGrpsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    private String triggerGroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @return the value of qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @param schedName the value for qrtz_paused_trigger_grps.SCHED_NAME
     *
     * @mbggenerated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @return the value of qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    public String getTriggerGroup() {
        return triggerGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @param triggerGroup the value for qrtz_paused_trigger_grps.TRIGGER_GROUP
     *
     * @mbggenerated
     */
    public void setTriggerGroup(String triggerGroup) {
        this.triggerGroup = triggerGroup;
    }
}