package com.haozi.demo.springboot.bean.po;

public class QrtzJobDetails extends QrtzJobDetailsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    private String jobClassName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated
     */
    private String isDurable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    private String isNonconcurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    private String isUpdateData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    private String requestsRecovery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_job_details.JOB_DATA
     *
     * @mbggenerated
     */
    private byte[] jobData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @return the value of qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.DESCRIPTION
     *
     * @param description the value for qrtz_job_details.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @return the value of qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    public String getJobClassName() {
        return jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_CLASS_NAME
     *
     * @param jobClassName the value for qrtz_job_details.JOB_CLASS_NAME
     *
     * @mbggenerated
     */
    public void setJobClassName(String jobClassName) {
        this.jobClassName = jobClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @return the value of qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated
     */
    public String getIsDurable() {
        return isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_DURABLE
     *
     * @param isDurable the value for qrtz_job_details.IS_DURABLE
     *
     * @mbggenerated
     */
    public void setIsDurable(String isDurable) {
        this.isDurable = isDurable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @return the value of qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public String getIsNonconcurrent() {
        return isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_NONCONCURRENT
     *
     * @param isNonconcurrent the value for qrtz_job_details.IS_NONCONCURRENT
     *
     * @mbggenerated
     */
    public void setIsNonconcurrent(String isNonconcurrent) {
        this.isNonconcurrent = isNonconcurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @return the value of qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    public String getIsUpdateData() {
        return isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.IS_UPDATE_DATA
     *
     * @param isUpdateData the value for qrtz_job_details.IS_UPDATE_DATA
     *
     * @mbggenerated
     */
    public void setIsUpdateData(String isUpdateData) {
        this.isUpdateData = isUpdateData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @return the value of qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public String getRequestsRecovery() {
        return requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.REQUESTS_RECOVERY
     *
     * @param requestsRecovery the value for qrtz_job_details.REQUESTS_RECOVERY
     *
     * @mbggenerated
     */
    public void setRequestsRecovery(String requestsRecovery) {
        this.requestsRecovery = requestsRecovery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_job_details.JOB_DATA
     *
     * @return the value of qrtz_job_details.JOB_DATA
     *
     * @mbggenerated
     */
    public byte[] getJobData() {
        return jobData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_job_details.JOB_DATA
     *
     * @param jobData the value for qrtz_job_details.JOB_DATA
     *
     * @mbggenerated
     */
    public void setJobData(byte[] jobData) {
        this.jobData = jobData;
    }
}