package com.haozi.demo.springboot.bean.po;

public class QrtzCalendarsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.SCHED_NAME
     *
     * @mbggenerated
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR_NAME
     *
     * @mbggenerated
     */
    private String calendarName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.SCHED_NAME
     *
     * @return the value of qrtz_calendars.SCHED_NAME
     *
     * @mbggenerated
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.SCHED_NAME
     *
     * @param schedName the value for qrtz_calendars.SCHED_NAME
     *
     * @mbggenerated
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.CALENDAR_NAME
     *
     * @return the value of qrtz_calendars.CALENDAR_NAME
     *
     * @mbggenerated
     */
    public String getCalendarName() {
        return calendarName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.CALENDAR_NAME
     *
     * @param calendarName the value for qrtz_calendars.CALENDAR_NAME
     *
     * @mbggenerated
     */
    public void setCalendarName(String calendarName) {
        this.calendarName = calendarName;
    }
}