package com.haozi.demo.springboot.bean.po;

public class QrtzCronTriggers extends QrtzCronTriggersKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    private String cronExpression;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    private String timeZoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @return the value of qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @param cronExpression the value for qrtz_cron_triggers.CRON_EXPRESSION
     *
     * @mbggenerated
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @return the value of qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    public String getTimeZoneId() {
        return timeZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @param timeZoneId the value for qrtz_cron_triggers.TIME_ZONE_ID
     *
     * @mbggenerated
     */
    public void setTimeZoneId(String timeZoneId) {
        this.timeZoneId = timeZoneId;
    }
}