package com.haozi.demo.springboot.bean.po;

public class QrtzSchedulerState extends QrtzSchedulerStateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    private Long checkinInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @return the value of qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for qrtz_scheduler_state.LAST_CHECKIN_TIME
     *
     * @mbggenerated
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @return the value of qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for qrtz_scheduler_state.CHECKIN_INTERVAL
     *
     * @mbggenerated
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}