package com.haozi.demo.springboot.bean.po;

public class QrtzCalendars extends QrtzCalendarsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qrtz_calendars.CALENDAR
     *
     * @mbggenerated
     */
    private byte[] calendar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qrtz_calendars.CALENDAR
     *
     * @return the value of qrtz_calendars.CALENDAR
     *
     * @mbggenerated
     */
    public byte[] getCalendar() {
        return calendar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qrtz_calendars.CALENDAR
     *
     * @param calendar the value for qrtz_calendars.CALENDAR
     *
     * @mbggenerated
     */
    public void setCalendar(byte[] calendar) {
        this.calendar = calendar;
    }
}