package com.haozi.demo.springboot.bean.po;

public class TposQueryInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpos_query_info.tpos_id
     *
     * @mbggenerated
     */
    private Integer tposId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tpos_query_info.tpos_key
     *
     * @mbggenerated
     */
    private String tposKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpos_query_info.tpos_id
     *
     * @return the value of tpos_query_info.tpos_id
     *
     * @mbggenerated
     */
    public Integer getTposId() {
        return tposId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpos_query_info.tpos_id
     *
     * @param tposId the value for tpos_query_info.tpos_id
     *
     * @mbggenerated
     */
    public void setTposId(Integer tposId) {
        this.tposId = tposId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tpos_query_info.tpos_key
     *
     * @return the value of tpos_query_info.tpos_key
     *
     * @mbggenerated
     */
    public String getTposKey() {
        return tposKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tpos_query_info.tpos_key
     *
     * @param tposKey the value for tpos_query_info.tpos_key
     *
     * @mbggenerated
     */
    public void setTposKey(String tposKey) {
        this.tposKey = tposKey;
    }
}