package com.fzrj.starter.service.dao;

import com.fzrj.starter.service.po.AquaticOrderUserInfo;

public interface AquaticOrderUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    int insert(AquaticOrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    int insertSelective(AquaticOrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    AquaticOrderUserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AquaticOrderUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aquatic_order_user_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AquaticOrderUserInfo record);
}