package com.haozi.component.oastruct.service.po;

import java.util.Date;

public class AquaticAllPriceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.price_key
     *
     * @mbggenerated
     */
    private String priceKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.shop_key
     *
     * @mbggenerated
     */
    private String shopKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.goods_key
     *
     * @mbggenerated
     */
    private String goodsKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.sku_key
     *
     * @mbggenerated
     */
    private String skuKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.price_mark_key
     *
     * @mbggenerated
     */
    private String priceMarkKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.current_price
     *
     * @mbggenerated
     */
    private Long currentPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.original_price
     *
     * @mbggenerated
     */
    private Long originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.start_num
     *
     * @mbggenerated
     */
    private Integer startNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aquatic_all_price_info.end_num
     *
     * @mbggenerated
     */
    private Integer endNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.id
     *
     * @return the value of aquatic_all_price_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.id
     *
     * @param id the value for aquatic_all_price_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.price_key
     *
     * @return the value of aquatic_all_price_info.price_key
     *
     * @mbggenerated
     */
    public String getPriceKey() {
        return priceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.price_key
     *
     * @param priceKey the value for aquatic_all_price_info.price_key
     *
     * @mbggenerated
     */
    public void setPriceKey(String priceKey) {
        this.priceKey = priceKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.shop_key
     *
     * @return the value of aquatic_all_price_info.shop_key
     *
     * @mbggenerated
     */
    public String getShopKey() {
        return shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.shop_key
     *
     * @param shopKey the value for aquatic_all_price_info.shop_key
     *
     * @mbggenerated
     */
    public void setShopKey(String shopKey) {
        this.shopKey = shopKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.goods_key
     *
     * @return the value of aquatic_all_price_info.goods_key
     *
     * @mbggenerated
     */
    public String getGoodsKey() {
        return goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.goods_key
     *
     * @param goodsKey the value for aquatic_all_price_info.goods_key
     *
     * @mbggenerated
     */
    public void setGoodsKey(String goodsKey) {
        this.goodsKey = goodsKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.sku_key
     *
     * @return the value of aquatic_all_price_info.sku_key
     *
     * @mbggenerated
     */
    public String getSkuKey() {
        return skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.sku_key
     *
     * @param skuKey the value for aquatic_all_price_info.sku_key
     *
     * @mbggenerated
     */
    public void setSkuKey(String skuKey) {
        this.skuKey = skuKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.price_mark_key
     *
     * @return the value of aquatic_all_price_info.price_mark_key
     *
     * @mbggenerated
     */
    public String getPriceMarkKey() {
        return priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.price_mark_key
     *
     * @param priceMarkKey the value for aquatic_all_price_info.price_mark_key
     *
     * @mbggenerated
     */
    public void setPriceMarkKey(String priceMarkKey) {
        this.priceMarkKey = priceMarkKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.current_price
     *
     * @return the value of aquatic_all_price_info.current_price
     *
     * @mbggenerated
     */
    public Long getCurrentPrice() {
        return currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.current_price
     *
     * @param currentPrice the value for aquatic_all_price_info.current_price
     *
     * @mbggenerated
     */
    public void setCurrentPrice(Long currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.original_price
     *
     * @return the value of aquatic_all_price_info.original_price
     *
     * @mbggenerated
     */
    public Long getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.original_price
     *
     * @param originalPrice the value for aquatic_all_price_info.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.status
     *
     * @return the value of aquatic_all_price_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.status
     *
     * @param status the value for aquatic_all_price_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.add_time
     *
     * @return the value of aquatic_all_price_info.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.add_time
     *
     * @param addTime the value for aquatic_all_price_info.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.update_time
     *
     * @return the value of aquatic_all_price_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.update_time
     *
     * @param updateTime the value for aquatic_all_price_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.start_num
     *
     * @return the value of aquatic_all_price_info.start_num
     *
     * @mbggenerated
     */
    public Integer getStartNum() {
        return startNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.start_num
     *
     * @param startNum the value for aquatic_all_price_info.start_num
     *
     * @mbggenerated
     */
    public void setStartNum(Integer startNum) {
        this.startNum = startNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aquatic_all_price_info.end_num
     *
     * @return the value of aquatic_all_price_info.end_num
     *
     * @mbggenerated
     */
    public Integer getEndNum() {
        return endNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aquatic_all_price_info.end_num
     *
     * @param endNum the value for aquatic_all_price_info.end_num
     *
     * @mbggenerated
     */
    public void setEndNum(Integer endNum) {
        this.endNum = endNum;
    }
}